Dumb-ways-to-memorize: dumb-ways-to-memorize/mymath.c File Reference
mymath.c File Reference
#include "globals.h"
#include <string.h>
#include <stdlib.h>
Functions
int LargestDivisor (int num)
void Vec2Add (vec2_t *A, vec2_t *B, vec2_t *C)
void Vec2Subtract (vec2_t *First, vec2_t *Second, vec2_t *C)
void Vec2MultiplyScalar (vec2_t *A, int B, vec2_t *C)
int CountMem (void *src, int size_type)
int AllocateDynamic (void **dst, void *src, int size_type, int size)
int CompareMemToMemArray (void *mem, void *mem_array, int size_type, int size_array)
Function Documentation
int AllocateDynamic (void ** dst, void * src, int size_type, int size)
Allocate memory and copy over src into it. Adds Null to end. Returns NULL on size 0
Parameters
[in,out] dst If non-null, destination for the allocation.
[in,out] src If non-null, source for the adding.
size_type Size of the type.
size The size.
Returns
0 on success, -1 on error.
Author
Anthony Rios
Date
2/1/2016
Definition at line 66 of file mymath.c.
Referenced by CopyObjectToObjectArray(), and ParseToObject().
 {
         int offset = size_type/sizeof(int);
         if(!dst) return -1;
         *dst = realloc(*dst, size_type*(size+1));
         if(!*dst) return -1;
         src ? memcpy((int*)(*dst)+(size-1)*offset, src, size_type) : memset((int*)(*dst)+(size-1)*offset, 0, size_type);
         memset((int*)(*dst)+(size)*offset, 0, size_type);
         return 0;
 }
int CompareMemToMemArray (void * mem, void * mem_array, int size_type, int size_array)
Compare memory to memory array.
Parameters
[in,out] mem If non-null, the memory.
[in,out] mem_array If non-null, array of memories.
size_type Size of type, via sizeof() function.
size_array Size of Array.
Returns
0 if equal, -1 if not.
Author
Anthony Rios
Date
1/31/2016
Definition at line 77 of file mymath.c.
Referenced by RandomizeSelectedLevels(), and SelectLevels().
 {
         int i, offset;
         int *memory = (int*) mem_array;
         offset = size_type;
         for(i = 0; i < size_array; i++)
         {
                 if(!memcmp(mem, memory, size_type))
                 {
                         return 0;
                 }
                 memory += offset;
         }
         return -1;
 }
int CountMem (void * src, int size_type)
Counts the memory of type size_type, given that the final address is null.
Parameters
[in,out] src If non-null, source of memory.
size_type Size of the type.
Returns
The total number of memory, if src is null 0 is returned.
Author
Anthony Rios
Date
2/1/2016
Definition at line 51 of file mymath.c.
Referenced by CopyObjectToObjectArray(), CountObjectChildren(), CountObjectMembers(), DoPlayerThink(), FindKey(), FindMenuItem(), FindPower(), FindValue(), IncrementFrame(), LoadEntityData(), LoadLevel(), LoadLevelData(), LoadMenu(), LoadMenuData(), LoadPowerUpData(), ParseAI(), ParsePresetAI(), ParseToEntity(), ParseToStringArray(), PrintObject(), ProcessMenuItemsByType(), RandomizeSelectedLevels(), StrToHazard(), TouchGeneric(), TouchGoal(), TouchPlayer(), UpdatePowerSelectMenu(), UpdatePowerUpMenu(), and UpdateVerticalMenu().
 {
         int i, offset;
         int *source = (int*)src;
         if(source == NULL)
                 return 0;
         i = 0; offset = size_type/sizeof(int);
         while( *(source) )
         {
                 source += offset;
                 i++;
         }
         return i;
 }
int LargestDivisor (int num)
Definition at line 5 of file mymath.c.
Referenced by ProcessMenuItemsByType().
 {
         int i, root, hit;
         hit = 0;
         root = num>>1;
         for(i = 0; i < root; i++)
         {
                 if(!num%i)
                 {
                         hit = i;
                 }
         }
         return hit;
 }
void Vec2Add (vec2_t * A, vec2_t * B, vec2_t * C)
Definition at line 20 of file mymath.c.
References vec2_t::x, and vec2_t::y.
Referenced by DoCollision(), JumpAI(), MoveAI(), RunPhysics(), Spawn(), and WalkAI().
 {
         if(!A || !B || !C)
         {
                 return;
         }
         C->x = A->x + B->x;
         C->y = A->y + B->y;
 }
void Vec2MultiplyScalar (vec2_t * A, int B, vec2_t * C)
Definition at line 41 of file mymath.c.
References vec2_t::x, and vec2_t::y.
Referenced by JumpAI(), MoveAI(), and WalkAI().
 {
         if(!A || !C)
         {
                 return;
         }
         (*C).x = A->x * B;
         (*C).y = A->y * B;
 }
void Vec2Subtract (vec2_t * First, vec2_t * Second, vec2_t * C)
Definition at line 31 of file mymath.c.
References vec2_t::x, and vec2_t::y.
 {
         if(!First || !Second || !C)
         {
                 return;
         }
         C->x = First->x - Second->x;
         C->y = First->y - Second->y;
 }