Dumb-ways-to-memorize: dumb-ways-to-memorize/parsefunction.h File Reference
parsefunction.h File Reference
#include "entity.h"
#include "SDL.h"
Functions
void * ParseToFunction (const char *name)
void GetWorld (entity_t *self, entity_t **targ)
void GetAtPoint (entity_t *self, entity_t **targ)
void GetSelf (entity_t *self, entity_t **targ)
void GetX (entity_t *self, int *button)
void GetMousePos (entity_t *self, vec2_t *pos)
void GetXMouse (entity_t *self, int *button, vec2_t *pos)
Variables
char * FunctionNames []
void *[] FunctionSymbols
Function Documentation
void GetAtPoint (entity_t * self, entity_t ** targ)
Gets the entity at the point specified by the mouse.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
[in,out] targ If non-null, the targ.
Author
Anthony Rios
Date
3/30/2016
Definition at line 31 of file parsefunction.c.
References GetMousePos(), and LookForEntityAtPos().
 {
         vec2_t *temp = (vec2_t*) malloc(sizeof(vec2_t));
         GetMousePos(self, temp);
         *targ = LookForEntityAtPos(*temp);
         free(temp);
         return;
 }
void GetMousePos (entity_t * self, vec2_t * pos)
Gets mouse position.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
[in,out] pos If non-null, the position.
Author
Anthony Rios
Date
3/30/2016
Definition at line 53 of file parsefunction.c.
References vec2_t::x, and vec2_t::y.
Referenced by CallInfo(), GetAtPoint(), and GetXMouse().
 {
         SDL_GetRelativeMouseState( &pos->x, &pos->y);
         return;
 }
void GetSelf (entity_t * self, entity_t ** targ)
Gets self and makes it targ.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
[in,out] targ If non-null, the targ.
Author
Anthony Rios
Date
3/30/2016
Definition at line 40 of file parsefunction.c.
 {
         *targ = self;
         return;
 }
void GetWorld (entity_t * self, entity_t ** targ)
Gets the world entities.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
[in,out] targ If non-null, the targ.
Author
Anthony Rios
Date
3/30/2016
Definition at line 25 of file parsefunction.c.
References gEntities.
 {
         *targ = gEntities;
         return;
 }
void GetX (entity_t * self, int * button)
Get the status of the button of the power_up.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
[in,out] button If non-null, the button.
Author
Anthony Rios
Date
3/30/2016
Definition at line 47 of file parsefunction.c.
Referenced by CallInfo(), and GetXMouse().
 {
         *button = SDL_GetKeyFromName("X");
         return;
 }
void GetXMouse (entity_t * self, int * button, vec2_t * pos)
Gets status of button and mouse position.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
[in,out] button If non-null, the button.
[in,out] pos If non-null, the position.
Author
Anthony Rios
Date
3/30/2016
Definition at line 59 of file parsefunction.c.
References GetMousePos(), and GetX().
Referenced by CallInfo().
 {
         GetX(self, button);
         GetMousePos(self, pos);
 }
void* ParseToFunction (const char * name)
Definition at line 11 of file parsefunction.c.
References FunctionNames, and FunctionSymbols.
Referenced by ParseToPowerUp().
 {
         int i;
         for(i = 0; FunctionNames[i]; i++)
         {
                 if(!strcmp(FunctionNames[i], name))
                 {
                         return FunctionSymbols[i];
                 }
         }
         return NULL;
 }
Variable Documentation
char* FunctionNames[]
Definition at line 8 of file parsefunction.c.
Referenced by ParseToFunction(), and ParseToPowerUp().
void*[] FunctionSymbols
Definition at line 9 of file parsefunction.c.
Referenced by ParseToFunction().