Dumb-ways-to-memorize: dumb-ways-to-memorize/game.h File Reference
game.h File Reference
Macros
#define SCREEN_RES_X 1280
#define SCREEN_RES_Y 720
#define JSON_FILE "GameData.json"
#define ENTITY_FILE "Entities.json"
#define SPLASH_SCREEN "SplashScreen"
#define LEVELS_NOT_DEFAULT "LevelsPerGame"
#define LIVES_DEFAULT 3
#define LEVELS_DEFAULT 6
Functions
int Setup ()
int Run ()
void Shutdown ()
Variables
int mState
Macro Definition Documentation
#define ENTITY_FILE "Entities.json"
Definition at line 8 of file game.h.
#define JSON_FILE "GameData.json"
Definition at line 7 of file game.h.
Referenced by LoadGameData().
#define LEVELS_DEFAULT 6
Definition at line 12 of file game.h.
Referenced by LoadLevelData().
#define LEVELS_NOT_DEFAULT "LevelsPerGame"
Definition at line 10 of file game.h.
Referenced by LoadLevelData().
#define LIVES_DEFAULT 3
Definition at line 11 of file game.h.
#define SCREEN_RES_X 1280
Definition at line 4 of file game.h.
#define SCREEN_RES_Y 720
Definition at line 5 of file game.h.
#define SPLASH_SCREEN "SplashScreen"
Definition at line 9 of file game.h.
Referenced by Update().
Function Documentation
int Run ()
Runs the main game loop.
Returns
An int.
Author
Anthony Rios
Date
3/29/2016
Definition at line 666 of file game.c.
References Draw(), exitRequest, FRAME_DELAY, gCurrentTime, gDelay, Poll(), and Update().
Referenced by main().
 {
         while(!exitRequest)
         {
                 Poll();
                 Update();
                 Draw();
                 gDelay = SDL_GetTicks() - gCurrentTime;
                 SDL_Delay(gDelay > FRAME_DELAY ? 0 : gDelay);
         }
         return 0;
 }
int Setup ()
Loads files and images for game.
Returns
state returns 0 on success, -1 on error
Author
Anthony Rios
Date
1/31/2016
Definition at line 592 of file game.c.
References gController, InitAISystem(), InitEntitySystem(), InitGraphics(), InitMenuSystem(), LoadEntityData(), LoadGameData(), LoadLevelData(), LoadMenuData(), LoadPowerUpData(), and SelectLevels().
Referenced by main().
 {
         //sprite_t *test_sprite;
         //vec2_t test_vec = {0,0};
         srand(SDL_GetTicks());
         //atexit(Shutdown);
         if(LoadGameData())
         {
                 perror("Loading game data went wrong");
                 return -1;
         }
         if(InitGraphics())
         {
                 perror("Initializing entity system went wrong");
                 return -1;
         }
         if(InitEntitySystem())
         {
                 perror("Initializing entity system went wrong");
                 return -1;
         }
         if(InitMenuSystem())
         {
                 perror("Initialize Menu system went wrong");
                 return -1;
         }
         if(InitAISystem())
         {
                 perror("Initialize AI system went wrong");
                 return -1;
         }
         if(LoadEntityData())
         {
                 perror("Loading entity data went wrong");
                 return -1;
         }
         if(LoadMenuData())
         {
                 perror("Shit Happens");
                 return -1;
         }
         if(LoadLevelData())
         {
                 perror("Loading level data went wrong");
                 return -1;
         }
         if(LoadPowerUpData())
         {
                 perror("Loading entity data went wrong");
                 return -1;
         }
         if(SelectLevels())
         {
                 perror("Selecting levels went wrong");
                 return -1;
         }
         gController = SDL_GameControllerOpen(0);
         //PrintObject(gLevelObject, gLevelData);
         //test_sprite = LoadSprite("Sprite/UI/NESController.png",0);
         //test_sprite->mCurrentFrame = LoadAnimation(test_sprite->mSize.x, test_sprite->mSize.y, test_sprite->mSize.x, test_sprite->mSize.y);
         //FreeSprite(test_sprite);
         return 0;
 }
void Shutdown ()
Definition at line 679 of file game.c.
Referenced by main().
 {
         return;
 }
Variable Documentation
int mState
Definition at line 14 of file game.h.