Dumb-ways-to-memorize: dumb-ways-to-memorize/External_Libs/jsmn.h File Reference
jsmn.h File Reference
#include <stddef.h>
Data Structures
struct jsmntok_t
struct jsmn_parser
Enumerations
enum jsmntype_t {
JSMN_UNDEFINED = 0,
JSMN_OBJECT = 1,
JSMN_ARRAY = 2,
JSMN_STRING = 3,
JSMN_PRIMITIVE = 4
}
enum jsmnerr {
JSMN_ERROR_NOMEM = -1,
JSMN_ERROR_INVAL = -2,
JSMN_ERROR_PART = -3
}
Functions
void jsmn_init (jsmn_parser *parser)
int jsmn_parse (jsmn_parser *parser, const char *js, size_t len, jsmntok_t *tokens, unsigned int num_tokens)
Enumeration Type Documentation
enum jsmnerr
Enumerator
JSMN_ERROR_NOMEM
JSMN_ERROR_INVAL
JSMN_ERROR_PART
Definition at line 25 of file jsmn.h.
              {
         /* Not enough tokens were provided */
         JSMN_ERROR_NOMEM = -1,
         /* Invalid character inside JSON string */
         JSMN_ERROR_INVAL = -2,
         /* The string is not a full JSON packet, more bytes expected */
         JSMN_ERROR_PART = -3
 };
enum jsmntype_t
JSON type identifier. Basic types are: o Object o Array o String o Other primitive: number, boolean (true/false) or null
Enumerator
JSMN_UNDEFINED
JSMN_OBJECT
JSMN_ARRAY
JSMN_STRING
JSMN_PRIMITIVE
Definition at line 17 of file jsmn.h.
              {
         JSMN_UNDEFINED = 0,
         JSMN_OBJECT = 1,
         JSMN_ARRAY = 2,
         JSMN_STRING = 3,
         JSMN_PRIMITIVE = 4
 } jsmntype_t;
Function Documentation
void jsmn_init (jsmn_parser * parser)
Create JSON parser over an array of tokens
Creates a new parser based over a given buffer with an array of tokens available.
Definition at line 306 of file jsmn.c.
References jsmn_parser::pos, jsmn_parser::toknext, and jsmn_parser::toksuper.
Referenced by ConvertFileToUseable().
{
         parser->pos = 0;
         parser->toknext = 0;
         parser->toksuper = -1;
 }
int jsmn_parse (jsmn_parser * parser, const char * js, size_t len, jsmntok_t * tokens, unsigned int num_tokens)
Run JSON parser. It parses a JSON data string into and array of tokens, each describing a single JSON object.
Parse JSON string and fill tokens.
Definition at line 151 of file jsmn.c.
References jsmntok_t::end, jsmn_alloc_token(), JSMN_ARRAY, JSMN_ERROR_INVAL, JSMN_ERROR_NOMEM, JSMN_ERROR_PART, JSMN_OBJECT, jsmn_parse_primitive(), jsmn_parse_string(), JSMN_STRING, jsmn_parser::pos, jsmntok_t::size, jsmntok_t::start, jsmn_parser::toknext, jsmn_parser::toksuper, and jsmntok_t::type.
Referenced by ConvertFileToUseable().
{
         int r;
         int i;
         jsmntok_t *token;
         int count = parser->toknext;
         for (; parser->pos < len && js[parser->pos] != '\0'; parser->pos++) {
                 char c;
                 jsmntype_t type;
                 c = js[parser->pos];
                 switch (c) {
                         case '{': case '[':
                                 count++;
                                 if (tokens == NULL) {
                                         break;
                                 }
                                 token = jsmn_alloc_token(parser, tokens, num_tokens);
                                 if (token == NULL)
                                         return JSMN_ERROR_NOMEM;
                                 if (parser->toksuper != -1) {
                                         tokens[parser->toksuper].size++;
 #ifdef JSMN_PARENT_LINKS
                                         token->parent = parser->toksuper;
 #endif
                                 }
                                 token->type = (c == '{' ? JSMN_OBJECT : JSMN_ARRAY);
                                 token->start = parser->pos;
                                 parser->toksuper = parser->toknext - 1;
                                 break;
                         case '}': case ']':
                                 if (tokens == NULL)
                                         break;
                                 type = (c == '}' ? JSMN_OBJECT : JSMN_ARRAY);
 #ifdef JSMN_PARENT_LINKS
                                 if (parser->toknext < 1) {
                                         return JSMN_ERROR_INVAL;
                                 }
                                 token = &tokens[parser->toknext - 1];
                                 for (;;) {
                                         if (token->start != -1 && token->end == -1) {
                                                 if (token->type != type) {
                                                         return JSMN_ERROR_INVAL;
                                                 }
                                                 token->end = parser->pos + 1;
                                                 parser->toksuper = token->parent;
                                                 break;
                                         }
                                         if (token->parent == -1) {
                                                 break;
                                         }
                                         token = &tokens[token->parent];
                                 }
 #else
                                 for (i = parser->toknext - 1; i >= 0; i--) {
                                         token = &tokens[i];
                                         if (token->start != -1 && token->end == -1) {
                                                 if (token->type != type) {
                                                         return JSMN_ERROR_INVAL;
                                                 }
                                                 parser->toksuper = -1;
                                                 token->end = parser->pos + 1;
                                                 break;
                                         }
                                 }
                                 /* Error if unmatched closing bracket */
                                 if (i == -1) return JSMN_ERROR_INVAL;
                                 for (; i >= 0; i--) {
                                         token = &tokens[i];
                                         if (token->start != -1 && token->end == -1) {
                                                 parser->toksuper = i;
                                                 break;
                                         }
                                 }
 #endif
                                 break;
                         case '\"':
                                 r = jsmn_parse_string(parser, js, len, tokens, num_tokens);
                                 if (r < 0) return r;
                                 count++;
                                 if (parser->toksuper != -1 && tokens != NULL)
                                         tokens[parser->toksuper].size++;
                                 break;
                         case '\t' : case '\r' : case '\n' : case ' ':
                                 break;
                         case ':':
                                 parser->toksuper = parser->toknext - 1;
                                 break;
                         case ',':
                                 if (tokens != NULL && parser->toksuper != -1 &&
                                                 tokens[parser->toksuper].type != JSMN_ARRAY &&
                                                 tokens[parser->toksuper].type != JSMN_OBJECT) {
 #ifdef JSMN_PARENT_LINKS
                                         parser->toksuper = tokens[parser->toksuper].parent;
 #else
                                         for (i = parser->toknext - 1; i >= 0; i--) {
                                                 if (tokens[i].type == JSMN_ARRAY || tokens[i].type == JSMN_OBJECT) {
                                                         if (tokens[i].start != -1 && tokens[i].end == -1) {
                                                                 parser->toksuper = i;
                                                                 break;
                                                         }
                                                 }
                                         }
 #endif
                                 }
                                 break;
 #ifdef JSMN_STRICT
                         /* In strict mode primitives are: numbers and booleans */
                         case '-': case '0': case '1' : case '2': case '3' : case '4':
                         case '5': case '6': case '7' : case '8': case '9':
                         case 't': case 'f': case 'n' :
                                 /* And they must not be keys of the object */
                                 if (tokens != NULL && parser->toksuper != -1) {
                                         jsmntok_t *t = &tokens[parser->toksuper];
                                         if (t->type == JSMN_OBJECT ||
                                                         (t->type == JSMN_STRING && t->size != 0)) {
                                                 return JSMN_ERROR_INVAL;
                                         }
                                 }
 #else
                         /* In non-strict mode every unquoted value is a primitive */
                         default:
 #endif
                                 r = jsmn_parse_primitive(parser, js, len, tokens, num_tokens);
                                 if (r < 0) return r;
                                 count++;
                                 if (parser->toksuper != -1 && tokens != NULL)
                                         tokens[parser->toksuper].size++;
                                 break;
 #ifdef JSMN_STRICT
                         /* Unexpected char in strict mode */
                         default:
                                 return JSMN_ERROR_INVAL;
 #endif
                 }
         }
         if (tokens != NULL) {
                 for (i = parser->toknext - 1; i >= 0; i--) {
                         /* Unmatched opened object or array */
                         if (tokens[i].start != -1 && tokens[i].end == -1) {
                                 return JSMN_ERROR_PART;
                         }
                 }
         }
         return count;
 }