Dumb-ways-to-memorize: dumb-ways-to-memorize/menu.c File Reference
menu.c File Reference
#include "globals.h"
#include "graphics.h"
#include "menu.h"
#include "mystrings.h"
#include <stdio.h>
#include <math.h>
#include <string.h>
#include "parsepowerup.h"
#include "parselevel.h"
#include "player.h"
Functions
void DeselectItemByNum (menu_t *self, int item)
void SelectItemByNum (menu_t *self, int item)
void UpdateVerticalMenu (menu_t *self, SDL_GameControllerButton button)
void UpdatePowerUpMenu (menu_t *self, SDL_GameControllerButton button)
void UpdatePowerSelectMenu (menu_t *self, SDL_GameControllerButton button)
int InitMenuSystem ()
void DrawMenuByNum (menu_t *self)
void DrawMenuByState (menu_t *self)
void ProcessMenuItemsByType (menu_item_t *items, menu_type_t type)
menu_t * LoadMenu (object_t *object, char *g_str, GameState curr_state, GameState previous_state)
menu_t * FindMenuFromGameState (GameState curr_state)
menu_t * FindFreeMenu ()
menu_item_t * FindMenuItem (menu_t *menu, char *item)
int StrToMenuType (char *str)
Variables
menu_t * gMenus = NULL
int gCurrentSelectedItem = 0
Function Documentation
void DeselectItemByNum (menu_t * self, int item)
Deselect item by number.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
item The item number to deselect.
Author
Anthony Rios
Date
3/29/2016
Definition at line 25 of file menu.c.
References MENU_ITEM_STATE_NOT_SELECTED.
Referenced by UpdateVerticalMenu().
 {
         if(!self)
         {
                 printf("Deselect item not given menu");
                 return;
         }
         self->mItems[item].State = MENU_ITEM_STATE_NOT_SELECTED;
 }
void DrawMenuByNum (menu_t * self)
Definition at line 317 of file menu.c.
References DrawSprite(), gCurrentSelectedItem, gRedTexture, and gRenderer.
Referenced by LoadMenu().
 {
         int i;
         SDL_Rect selection_rect = {0,0,10,10};
         if(!self)
         {
                 printf("Null menu tried to be drawn \n");
                 return;
         }
         if(self->mBackground)
         {
                 if(DrawSprite(self->mBackground, NULL , NULL, gRenderer))
                 {
                         printf("Failed to draw Background \n");
                         return;
                 }
         }
         for(i = 0; i < self->mItemCount; i++)
         {
                 if( i == gCurrentSelectedItem )
                 {
                         if(DrawSprite(self->mItems[i].Image, NULL , &self->mItems[i].Position, gRenderer))
{
                                 printf("Failed to draw Menu Item : %d \n", i);
                                 return;
                         }
                         selection_rect.x = self->mItems[i].Position.x;
                         selection_rect.y = self->mItems[i].Position.y;
                         SDL_RenderCopy(gRenderer, gRedTexture, &selection_rect,&selection_rect);
                 } else {
                         if(DrawSprite(self->mItems[i].Image, NULL, &self->mItems[i].Position, gRenderer))
{
                                 printf("Failed to draw Menu Item : %d \n", i);
                                 return;
                         }
                 }
         }
 }
void DrawMenuByState (menu_t * self)
Definition at line 361 of file menu.c.
References DrawSprite(), gRedTexture, gRenderer, and MENU_ITEM_STATE_PICKED.
Referenced by LoadMenu().
 {
         int i;
         SDL_Rect selection_rect = {0,0,10,10};
         if(!self)
         {
                 printf("Null menu tried to be drawn \n");
                 return;
         }
         if(self->mBackground)
         {
                 DrawSprite(self->mBackground, NULL , NULL, gRenderer);
         }
         for(i = 0; i < self->mItemCount; i++)
         {
                 if( (self->mItems[i].State & MENU_ITEM_STATE_PICKED) || (&self->mItems[i] == self->mSelectedItem))
                 {
                         if(DrawSprite(self->mItems[i].Image, NULL , &self->mItems[i].Position, gRenderer))
{
                                 printf("Failed to draw Menu Item : %d \n", i);
                                 return;
                         }
                         selection_rect.x = self->mItems[i].Position.x;
                         selection_rect.y = self->mItems[i].Position.y;
                         SDL_RenderCopy(gRenderer, gRedTexture, &selection_rect,&selection_rect);
                 }
                 else
                 {
                         if(DrawSprite(self->mItems[i].Image, NULL , &self->mItems[i].Position, gRenderer))
{
                                 printf("Failed to draw Menu Item : %d \n", i);
                                 return;
                         }
                 }
         }
 }
menu_t* FindFreeMenu ()
Searches for the first free menu slot in gMenus, used for loading new menus.
Returns
null if it fails, else the found free menu.
Author
Anthony Rios
Date
3/30/2016
Definition at line 659 of file menu.c.
References gMenus, and MAX_MENUS.
Referenced by LoadMenu().
 {
         int i, *menuCmp;
         if(!gMenus)
         {
                 printf("Menu System not initialized");
                 return NULL;
         }
         menuCmp = (int*) malloc(sizeof(menu_t));
         memset(menuCmp, 0, sizeof(menu_t));
         for(i = 0; i < MAX_MENUS; i++)
         {
                 if(!memcmp(menuCmp, &gMenus[i], sizeof(menu_t)))
                 {
                         return &gMenus[i];
                 }
         }
         return NULL;
 }
menu_t* FindMenuFromGameState (GameState curr_state)
Searches for the first menu from game state in gMenus.
Parameters
curr_state State of the curr.
Returns
null if it fails, else the found menu from game state.
Author
Anthony Rios
Date
3/16/2016
Definition at line 637 of file menu.c.
References gMenus, MAX_MENUS, and Update().
Referenced by LoadMenu().
 {
         int i;
         if(!gMenus)
         {
                 printf("Menu Sys not Initialized");
                 return NULL;
         }
         for(i = 0; i < MAX_MENUS; i++)
         {
                 if(!gMenus[i].Update)
                 {
                         continue;
                 }
                 if(gMenus[i].mCurrentState == curr_state)
                 {
                         return &gMenus[i];
                 }
         }
         return NULL;
 }
menu_item_t* FindMenuItem (menu_t * menu, char * item)
Searches for the first menu item, with name of str given.
Parameters
[in,out] menu If non-null, the menu.
[in,out] item If non-null, the item.
Returns
null if it fails, else the found menu item.
Author
Anthony Rios
Date
3/30/2016
Definition at line 679 of file menu.c.
References CountMem().
Referenced by LoadMenu().
 {
         int i, items;
         items = CountMem(menu->mItems, sizeof(menu_item_t));
         for(i = 0; i < items; i++)
         {
                 if(!menu->mItems[i].Name)
                 {
                         continue;
                 }
                 if(!strcmp(item, menu->mItems[i].Name))
                 {
                         return &menu->mItems[i];
                 }
         }
         return NULL;
 }
int InitMenuSystem ()
Allocate memor for menu system, gMenus is the menu list.
Author
Anthony Rios
Date
3/16/2016
Definition at line 299 of file menu.c.
References gMenus, and MAX_MENUS.
Referenced by LoadMenuData(), and Setup().
 {
         if(gMenus)
         {
                 printf("gMenus already initialized");
                 return -1;
         }
         gMenus = (menu_t*) malloc(sizeof(menu_t)*MAX_MENUS);
         if(!gMenus)
         {
                 printf("Allocate menu error");
                 return -1;
         }
         memset(gMenus, 0, sizeof(menu_t)*MAX_MENUS);
         return 0;
 }
menu_t* LoadMenu (object_t * object, char * g_str, GameState curr_state, GameState previous_state)
Loads a menu.
Parameters
[in,out] object If non-null, the object menu was parsed to.
[in,out] g_str If non-null, the string.
curr_state State to assign the menu.
previous_state State before this menu.
Returns
0 if loads correctly, -1 if it doesn't.
Author
Anthony Rios
Date
3/16/2016
Definition at line 478 of file menu.c.
References CountMem(), CountObjectChildren(), DrawMenuByNum(), DrawMenuByState(), FindFreeMenu(), FindMenuFromGameState(), FindMenuItem(), FindObject(), FindValue(), gSelectedPowerUps, GUESS, LoadSprite(), MENU_BACKGROUND, MENU_ITEM_EXTRA, MENU_ITEM_LINK, MENU_ITEM_MAX, MENU_ITEM_SPRITE, MENU_ITEM_STATE_NOT_SELECTED, MENU_ITEM_STATE_SELECTED, MENU_ITEM_TEXT, MENU_ITEMS, MENU_TYPE, MENU_TYPE_STR_CHOOSE, MENU_TYPE_STR_POWER, MENU_TYPE_STR_V, PLAYING, ProcessMenuItemsByType(), SPLASH, StrToGameState(), StrToMenuType(), UpdatePowerSelectMenu(), UpdatePowerUpMenu(), and UpdateVerticalMenu().
Referenced by LoadMenuData(), and UpdatePowerUpMenu().
 {
         menu_t *menu, *ref_menu;
         menu_item_t *ref_menu_item;
         object_t *temp_obj;
         char *temp_str, *type_str, *bg_str;
         int i, temp_i, choose_i;
         //Check Vars given
         if(!object || !g_str)
         {
                 printf("No object / str given to load menu \n");
                 return NULL;
         }
         //Look for free menu slot
         menu = FindFreeMenu();
         if(!menu)
         {
                 printf("Could not find free menu \n");
                 return NULL;
         }
         menu->mPreviousState = previous_state;
         menu->mCurrentState = curr_state;
         temp_obj = FindObject(object, MENU_ITEMS);
         if(!temp_obj)
         {
                 printf("No items in menu %s \n", object->name);
                 return NULL;
         }
         //Load Background
         bg_str = FindValue(object, MENU_BACKGROUND, g_str);
         if(!bg_str)
         {
                 printf("No background loaded for menu %s \n", object->name);
         } else
         {
                 menu->mBackground = LoadSprite(bg_str, 0);
         }
         //Check menu type
         type_str = FindValue(object, MENU_TYPE, g_str);
         if(!type_str)
         {
                 printf("Not found menu layout type for %s. Switching to default vertical layout", object->name);
                 type_str = strdup(MENU_TYPE_STR_V);
         }
         //Load Items
         temp_i = CountObjectChildren(temp_obj);
         if(temp_i >= MENU_ITEM_MAX)
         {
                 printf("Max menu items for menu %s \n", object->name);
                 temp_i = MENU_ITEM_MAX -1;
         }
         menu->mItemCount = temp_i;
         for(i = 0; i < temp_i; i++)
         {
                 menu->mItems[i].State = MENU_ITEM_STATE_NOT_SELECTED;
                 menu->mItems[i].Info = NULL;
                 temp_str = FindValue(&temp_obj->children[i], MENU_ITEM_SPRITE, g_str);
                 if(temp_str)
                 {
                         menu->mItems[i].Image = LoadSprite(temp_str, 0);
                 }
                 temp_str = FindValue(&temp_obj->children[i], MENU_ITEM_TEXT, g_str);
                 if(temp_str)
                 {
                         menu->mItems[i].Name = temp_str;
                 }
                 temp_str = FindValue(&temp_obj->children[i], MENU_ITEM_LINK, g_str);
                 if(temp_str)
                 {
                         menu->mItems[i].NextState = StrToGameState(temp_str);
                         if(temp_str) free(temp_str);
                 } else
                 {
                         menu->mItems[i].NextState = SPLASH;
                 }
                 temp_str = FindValue(&temp_obj->children[i], MENU_ITEM_EXTRA, g_str);
                 if(temp_str)
                 {
                         menu->mItems[i].Info = temp_str;
                         if(!menu->mItems[i].Name)
{
                                 menu->mItems[i].Name = temp_str;
                         }
                 } else
                 {
                         menu->mItems[i].Info = NULL;
                 }
         }
         //Load extra items
         if(!strcmp(type_str, MENU_TYPE_STR_CHOOSE))
         {
                 choose_i = CountMem(gSelectedPowerUps, sizeof(char*));
                 ref_menu = FindMenuFromGameState(GUESS);
                 if(!ref_menu)
                 {
                         printf("Trouble loading choose menu , no GUESS menu found \n");
                 }
                 else
                 {
                         for(i = 0; i < choose_i; i++)
{
                                 ref_menu_item = FindMenuItem(ref_menu, gSelectedPowerUps[i]);
                                 if(!ref_menu_item)
{
                                         continue;
                                 }
                                 memcpy(&menu->mItems[menu->mItemCount+i], ref_menu_item, sizeof(menu_item_t));
                                 menu->mItems[menu->mItemCount+i].State = MENU_ITEM_STATE_NOT_SELECTED;
                                 menu->mItems[menu->mItemCount+i].NextState = PLAYING;
                         }
                         menu->mItemCount += choose_i;
                 }
         }
         //Calculate Menu Item Positions
         ProcessMenuItemsByType(menu->mItems, (menu_type_t) StrToMenuType(type_str));
         menu->mSelectedItem = menu->mItems;
         menu->mSelectedItem->State = MENU_ITEM_STATE_SELECTED;
         //gCurrentSelectedItem = 0;
         //Set Up Different Menu Types
         if(!strcmp(type_str, MENU_TYPE_STR_V))
         {
                 menu->Update = UpdateVerticalMenu;
                 menu->Draw = DrawMenuByNum;
         } else if(!strcmp(type_str, MENU_TYPE_STR_POWER))
         {
                 menu->Update = UpdatePowerUpMenu;
                 menu->Draw = DrawMenuByState;
         } else if (!strcmp(type_str, MENU_TYPE_STR_CHOOSE))
         {
                 menu->Update = UpdatePowerSelectMenu;
                 menu->Draw = DrawMenuByState;
         } else
         {
                 menu->Update = UpdateVerticalMenu;
                 menu->Draw = DrawMenuByNum;
         }
         return menu;
 }
void ProcessMenuItemsByType (menu_item_t * items, menu_type_t type)
Sets the positions of the menu items based on the type of layout.
Parameters
[in,out] items If non-null, the items.
type The type.
Author
Anthony Rios
Date
3/16/2016
Definition at line 413 of file menu.c.
References CountMem(), gScreenHeight, gScreenWidth, LargestDivisor(), MENU_TYPE_CHOOSE, MENU_TYPE_GRID, MENU_TYPE_H, MENU_TYPE_POWER, MENU_TYPE_V, SCREEN_RES_H, SCREEN_RES_W, and SDL_SetRect().
Referenced by LoadMenu().
 {
         SDL_Rect format;
         int itemCount, i, width, height, divisor;
         float radius;
         itemCount = CountMem(items, sizeof(menu_item_t));
         divisor = 0; radius = 0;
         width = gScreenWidth ? gScreenWidth : SCREEN_RES_W;
         height = gScreenHeight ? gScreenHeight : SCREEN_RES_H;
         switch(type)
         {
         case(MENU_TYPE_H):
                 {
                         SDL_SetRect(&format, 0, height/(itemCount+1), 0, 0);
                         break;
                 }
         case(MENU_TYPE_V) :
                 {
                         SDL_SetRect(&format, width/(itemCount+1), 0, 0, 0);
                         break;
                 }
         case(MENU_TYPE_GRID):
                 {
                         SDL_SetRect(&format, width/(itemCount+1), height/(itemCount+1), 0, 0);
                         divisor = LargestDivisor(itemCount);
                         break;
                 }
         case(MENU_TYPE_POWER):
                 {
                         //Center of Screen
                         SDL_SetRect(&format, width/2, height/2, 0, 0);
                         radius = (float) height/3;
                         break;
                 }
         default:
                 {
                         SDL_SetRect(&format, 0, height/(itemCount+1), 0, 0);
                         break;
                 }
         }
         for(i = 0; i < itemCount; i++)
         {
                 if(type & (MENU_TYPE_H | MENU_TYPE_V | MENU_TYPE_CHOOSE))
                 {
                         items[i].Position.x = format.x * i;
                         items[i].Position.y = format.y * i;
                 }
                 if(type & MENU_TYPE_GRID)
                 {
                         items[i].Position.x = format.x * i%divisor;
                         items[i].Position.y = format.y * i/divisor;
                 }
                 if(type & MENU_TYPE_POWER)
                 {
                         items[i].Position.x = format.x - (float) radius*sinf( 3.14 * (float) i/(itemCount+1));
                         items[i].Position.y = format.y - (float) radius*cosf( 3.14 * (float) i/(itemCount+1));
                 }
         }
 }
void SelectItemByNum (menu_t * self, int item)
Select item by number.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
item The item number to select.
Author
Anthony Rios
Date
3/29/2016
Definition at line 45 of file menu.c.
References MENU_ITEM_STATE_SELECTED.
Referenced by UpdateVerticalMenu().
 {
         if(!self)
         {
                 printf("Select item not given menu");
                 return;
         }
         self->mItems[item].State = MENU_ITEM_STATE_SELECTED;
 }
int StrToMenuType (char * str)
Converts a string into a menu type
Definition at line 697 of file menu.c.
References MENU_TYPE_CHOOSE, MENU_TYPE_GRID, MENU_TYPE_H, MENU_TYPE_NULL, MENU_TYPE_POWER, MENU_TYPE_STR_CHOOSE, MENU_TYPE_STR_GRID, MENU_TYPE_STR_H, MENU_TYPE_STR_POWER, MENU_TYPE_STR_V, and MENU_TYPE_V.
Referenced by LoadMenu().
 {
         if(!strcmp(str, MENU_TYPE_STR_H))
         {
                 return MENU_TYPE_H;
         }
         if(!strcmp(str, MENU_TYPE_STR_V))
         {
                 return MENU_TYPE_V;
         }
         if(!strcmp(str, MENU_TYPE_STR_GRID))
         {
                 return MENU_TYPE_GRID;
         }
         if(!strcmp(str, MENU_TYPE_STR_POWER))
         {
                 return MENU_TYPE_POWER;
         }
         if(!strcmp(str, MENU_TYPE_STR_CHOOSE))
         {
                 return MENU_TYPE_CHOOSE;
         }
         return MENU_TYPE_NULL;
 }
void UpdatePowerSelectMenu (menu_t * self, SDL_GameControllerButton button)
Updates the power select menu, sets current powerup of the player.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
button The button.
Author
Anthony Rios
Date
3/29/2016
Definition at line 234 of file menu.c.
References CountMem(), FindPower(), gCurrentPowerUp, gCurrentPowerUpName, gGameState, gSelectedPowerUps, gUsedPowerUps, InitPlayer(), LoadSelectedLevel(), MENU_ITEM_STATE_NULL, and PLAYING.
Referenced by LoadMenu().
 {
         int i, powerUps, usedPower = 1;
         if(!self)
         {
                 printf("NULL menu updated \n");
                 return;
         }
         switch(button)
         {
         case(SDL_CONTROLLER_BUTTON_DPAD_UP):
                 {
                         if(self->mSelectedItem-1 < self->mItems)
{
                                 break;
                         }
                         self->mSelectedItem--;
                         break;
                 }
         case(SDL_CONTROLLER_BUTTON_DPAD_DOWN):
                 {
                         if(self->mSelectedItem+1 == self->mItems+self->mItemCount)
{
                                 break;
                         }
                         self->mSelectedItem++;
                         break;
                 }
         case(SDL_CONTROLLER_BUTTON_A):
                 {
                         if(self->mSelectedItem->State != MENU_ITEM_STATE_NULL)
{
                                 powerUps = CountMem(gSelectedPowerUps, sizeof(char*));
                                 for(i = 0; i < powerUps; i++)
{
                                         if(!gUsedPowerUps[i])
{
                                                 gUsedPowerUps[i] = self->mSelectedItem[i].Name;
                                                 usedPower = 0;
                                                 break;
                                         } else if(!strcmp(self->mSelectedItem[i].Name, gUsedPowerUps[i]))
{
                                                 break;
                                         }
                                 }
                                 if(!usedPower)
{
                                         gCurrentPowerUpName = self->mSelectedItem[i].Name;
                                         gCurrentPowerUp = FindPower(gCurrentPowerUpName);
                                         LoadSelectedLevel(i);
                                         gGameState = self->mSelectedItem[i].NextState;
                                         if(gGameState == PLAYING)
{
                                                 InitPlayer();
                                         }
                                 }
                         }
                 }
         default:
                 break;
         }
 }
void UpdatePowerUpMenu (menu_t * self, SDL_GameControllerButton button)
Uses mSelectedItem. Updates the menu's selected item, and checks for number of power ups selected, to determine whether to switch game states.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
button The button.
Author
Anthony Rios
Date
3/29/2016
Definition at line 125 of file menu.c.
References CHOOSE, ConvertFileToUseable(), CountMem(), FindObject(), gGameData, gGameObject, gGameState, gLevelsPerGame, gPowerUps, gSelectedPowerUps, GUESS, gUsedPowerUps, JsmnToString(), LoadMenu(), MENU_ITEM_STATE_NOT_SELECTED, MENU_ITEM_STATE_PICKED, ParseToObject(), and SPLASH.
Referenced by LoadMenu().
 {
         int i, powerUps, selected_power_ups;
         object_t *temp, *choose_obj;
         jsmntok_t *choose_tok;
         char *choose_data;
         if(!self)
         {
                 printf("NULL menu updated \n");
                 return;
         }
         switch(button)
         {
         case(SDL_CONTROLLER_BUTTON_DPAD_UP):
                 {
                         if(!self->mSelectedItem)
{
                                 self->mSelectedItem = self->mItems;
                         }
                         if(self->mSelectedItem-1 < self->mItems)
{
                                 break;
                         }
                         self->mSelectedItem--;
                         break;
                 }
         case(SDL_CONTROLLER_BUTTON_DPAD_DOWN):
                 {
                         if(!self->mSelectedItem)
{
                                 self->mSelectedItem = self->mItems;
                         }
                         if(self->mSelectedItem+1 == self->mItems+self->mItemCount)
{
                                 break;
                         }
                         self->mSelectedItem++;
                         break;
                 }
         case(SDL_CONTROLLER_BUTTON_A):
                 {
                         if(!self->mSelectedItem)
{
                                 self->mSelectedItem = self->mItems;
                         }
                         if(self->mSelectedItem->NextState == SPLASH)
{
                                 self->mSelectedItem->State = (menu_item_state_t) (~self->mSelectedItem->State & MENU_ITEM_STATE_PICKED);
                         } else
{
                                 powerUps = CountMem(gPowerUps, sizeof(power_t));
                                 gSelectedPowerUps = (char**) malloc(sizeof(char*)*(powerUps+1));
                                 memset(gSelectedPowerUps, 0, sizeof(char*)*(powerUps+1));
                                 selected_power_ups = 0;
                                 for(i = 0; i < powerUps; i++)
{
                                         if(self->mItems[i].State & MENU_ITEM_STATE_PICKED)
{
                                                 gSelectedPowerUps[selected_power_ups] = gPowerUps[i].name;
                                                 selected_power_ups++;
                                         }
                                 }
                                 if(selected_power_ups != gLevelsPerGame)
{
                                         printf("Too many or not enough power_ups selected");
                                         for(i = 0; i < selected_power_ups; i++)
{
                                                 gSelectedPowerUps[i] = NULL;
                                         }
                                         if(gSelectedPowerUps) free(gSelectedPowerUps);
                                         break;
                                 }
                                 gUsedPowerUps = (char**) malloc(sizeof(char*)*(selected_power_ups+1));
                                 memset(gUsedPowerUps, 0, sizeof(char*)*(selected_power_ups+1));
                                 gSelectedPowerUps[selected_power_ups] = NULL;
                                 temp = FindObject(gGameObject, "Menus");
                                 ConvertFileToUseable(JsmnToString(&temp->values[2], gGameData), NULL, &choose_data, &choose_tok);
                                 choose_obj = ParseToObject(choose_tok, choose_data);
                                 if(!LoadMenu(choose_obj, choose_data, CHOOSE, GUESS))
{
                                         printf("Failure to load Choose Menu \n");
                                         return;
                                 }
                                 for(i = 0; i < self->mItemCount; i++)
{
                                         self->mItems[i].State = MENU_ITEM_STATE_NOT_SELECTED;
                                 }
                                 self->mSelectedItem = NULL;
                                 gGameState = CHOOSE;
                         }
                         break;
                 }
         default:
                 {
                         break;
                 }
         }
 }
void UpdateVerticalMenu (menu_t * self, SDL_GameControllerButton button)
Uses gSelectedItem. Updates input and state of menu items.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
button The button.
Author
Anthony Rios
Date
3/29/2016
Definition at line 65 of file menu.c.
References CountMem(), DeselectItemByNum(), gCurrentSelectedItem, gGameState, and SelectItemByNum().
Referenced by LoadMenu().
 {
         if(!self)
         {
                 printf("NULL menu updated \n");
                 return;
         }
         switch(button)
         {
         case(SDL_CONTROLLER_BUTTON_DPAD_UP):
                 {
                         if(!gCurrentSelectedItem)
{
                                 break;
                         }
                         DeselectItemByNum(self, gCurrentSelectedItem);
                         if(gCurrentSelectedItem-1 < 0)
{
                                 SelectItemByNum(self, gCurrentSelectedItem);
                                 break;
                         }
                         gCurrentSelectedItem--;
                         SelectItemByNum(self, gCurrentSelectedItem);
                         break;
                 }
         case(SDL_CONTROLLER_BUTTON_DPAD_DOWN):
                 {
                         DeselectItemByNum(self, gCurrentSelectedItem);
                         if(gCurrentSelectedItem+1 == CountMem(self->mItems, sizeof(menu_item_t)))
{
                                 SelectItemByNum(self, gCurrentSelectedItem);
                                 break;
                         }
                         gCurrentSelectedItem++;
                         SelectItemByNum(self, gCurrentSelectedItem);
                         break;
                 }
         case(SDL_CONTROLLER_BUTTON_A):
                 {
                         gGameState = self->mItems[gCurrentSelectedItem].NextState;
                         break;
                 }
         default:
                 {
                         break;
                 }
         }
 }
Variable Documentation
int gCurrentSelectedItem = 0
Definition at line 13 of file menu.c.
Referenced by DrawMenuByNum(), and UpdateVerticalMenu().
menu_t* gMenus = NULL
Definition at line 12 of file menu.c.
Referenced by DrawChoose(), DrawGuess(), DrawStart(), FindFreeMenu(), FindMenuFromGameState(), InitMenuSystem(), LoadMenuData(), and Update().