Dumb-ways-to-memorize: dumb-ways-to-memorize/mystrings.c File Reference
mystrings.c File Reference
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <stdio.h>
#include <math.h>
#include "globals.h"
#include "mystrings.h"
#include "parseobject.h"
Enumerations
enum FreeVar {
PARSER = 0x1,
STRING = 0x2,
TOKEN = 0x4
}
Functions
jsmntok_t * FindKey (jsmntok_t *token, char *key, char *g_str)
char * JsmnToString (jsmntok_t *token, char *g_str)
char * FindValue (struct object_s *obj, char *key, char *g_str)
void JsmnToInt (jsmntok_t *token, char *str, int *dst)
int StrToInt (char *str)
int CharToInt (char c)
char * TypeFromJSON (jsmntype_t Type)
char * FileToString (char *fileName)
int ConvertFileToUseable (char *fileName, jsmn_parser *parser, char **stringStorage, jsmntok_t **jsmnStorage)
GameState StrToGameState (char *str)
int StrToHazard (char *str)
collision_type_t StrToCollisionType (char *str)
entity_state_t StrToEntityState (char *str)
vec2_t * ParseToVec2 (object_t *object, char *str)
char ** ParseToStringArray (object_t *object, char *str)
Enumeration Type Documentation
enum FreeVar
Enumerator
PARSER
STRING
TOKEN
Definition at line 185 of file mystrings.c.
 {
         PARSER= 0x1,
         STRING= 0x2,
         TOKEN=  0x4
 };
Function Documentation
int CharToInt (char c)
Character to int. A cheap switch statement.
Parameters
c The character.
Returns
An int.
Author
Anthony Rios
Date
2/28/2016
Definition at line 121 of file mystrings.c.
Referenced by StrToInt().
 {
         switch(c)
         {
         case '0': return 0;
         case '1': return 1;
         case '2': return 2;
         case '3': return 3;
         case '4': return 4;
         case '5': return 5;
         case '6': return 6;
         case '7': return 7;
         case '8': return 8;
         case '9': return 9;
         default:
                 return 0;
         }
 }
int ConvertFileToUseable (char * fileName, jsmn_parser * parser, char ** stringStorage, jsmntok_t ** jsmnStorage)
Convert file to useable, by setting the storage for string and jsmntokens, give a filename.
Parameters
[in,out] fileName If non-null, filename of the file.
[in,out] parser If non-null, the parser.
[in,out] stringStorage If non-null, the string storage.
[in,out] jsmnStorage If non-null, the jsmn storage.
Returns
The file converted to useable.
Author
Anthony Rios
Date
3/29/2016
Definition at line 192 of file mystrings.c.
References FileToString(), jsmn_init(), jsmn_parse(), PARSER, STRING, and TOKEN.
Referenced by LoadEntityData(), LoadGameData(), LoadLevel(), LoadMenuData(), LoadPowerUpData(), LoadSelectedLevel(), SetAI_Check(), and UpdatePowerUpMenu().
 {
         int num_tokens, varsToFree = 0;
         jsmn_parser *tempPars;
         char **tempStr;
         jsmntok_t **tempJsmn;
         if(!fileName)
         {
                 printf("Convert File given NULL filename");
                 return -1;
         }
         //Init parser, if not given
         if(!parser)
         {
                 tempPars = (jsmn_parser*) malloc(sizeof(parser));
                 if(!tempPars) return -1;
                 parser = tempPars;
                 varsToFree |= PARSER;
         }
         jsmn_init(parser);
         //Init stringStorage if not given
         if(!stringStorage)
         {
                 tempStr = (char**) malloc(sizeof(char*));
                 if(!tempStr) return -1;
                 stringStorage = tempStr;
                 varsToFree |= STRING;
         }
         *stringStorage = FileToString(fileName);
         if(!*stringStorage)
         {
                 return -1;
         }
         //Init jsmnStorage if not given
         if(!jsmnStorage)
         {
                 tempJsmn = (jsmntok_t**) malloc(sizeof(jsmntok_t*));
                 if(!tempJsmn) return -1;
                 jsmnStorage = tempJsmn;
                 varsToFree |= TOKEN;
         }
         //Actual Parsing
         num_tokens = jsmn_parse(parser, *stringStorage, strlen(*stringStorage), NULL, 0);
         if(num_tokens < 1)
         {
                 printf("Jsmn Parse Eror: %d", num_tokens);
                 return -1;
         }
         *jsmnStorage = (jsmntok_t*) malloc(sizeof(jsmntok_t)*(num_tokens+1));
         if(!*jsmnStorage)
         {
                 return -1;
         }
         jsmn_init(parser); //Reset parser
         num_tokens = jsmn_parse(parser, *stringStorage, strlen(*stringStorage), *jsmnStorage, num_tokens);
         printf("Jsmn returned : %d\n", num_tokens);
         memset( &(*jsmnStorage)[num_tokens], 0, sizeof(jsmntok_t));
         //Freeing if necessary
         if(varsToFree & PARSER) ;
         if(varsToFree & STRING) free(*stringStorage);
         if(varsToFree & TOKEN) free(*jsmnStorage);
         return num_tokens;
 }
char* FileToString (char * file)
Loads string data from a file.
Parameters
[in,out] file If non-null, filename of the file.
Returns
null if it fails, else a char*.
Author
Anthony Rios
Date
1/30/2016
Definition at line 159 of file mystrings.c.
References ALLOC_STR.
Referenced by ConvertFileToUseable().
 {
         char *string;
         int size;
         struct stat st;
         FILE *file;
         stat(fileName, &st);
         file = fopen(fileName, "r");
         if(!file)
         {
                 return NULL;
         }
         size = st.st_size;
         string = ALLOC_STR(size);
         if(!string)
         {
                 printf("Could not allocate memory");
                 exit(-1);
         }
         size = fread(string, sizeof(unsigned char), size, file);
         string[size] = '\0';
         fclose(file);
         return string;
 }
jsmntok_t* FindKey (jsmntok_t * token, char * key, char * g_str)
Searches for the first key that matches given gPlayerName, through through tokens & g_str.
Parameters
[in,out] token The token.
[in,out] key The key.
[in,out] g_str The string to get from.
Returns
null if it fails, else the found key.
Author
Junji
Date
1/30/2016
Definition at line 10 of file mystrings.c.
References CountMem(), JsmnToString(), and jsmntok_t::size.
Referenced by LoadEntityData(), LoadLevel(), LoadLevelData(), ParseAI(), ParsePresetAI(), and ParseToEntity().
 {
         char *str;
         jsmntok_t *local_token = token;
         jsmntok_t* endPtr = token + CountMem(token, sizeof(jsmntok_t));
         if(!local_token || !g_str || !key)
                 return local_token;
         while(local_token < endPtr)
         {
                 if(local_token->size == 1)
                 {
                         str = JsmnToString(local_token, g_str);
                         if(!strcmp(str, key))
{
                                 if(str) free(str);
                                 return local_token;
                         }
                         if(str) free(str);
                 }
                 local_token++;
         }
         return NULL;
 }
char* FindValue (struct object_s * obj, char * key, char * g_str)
Searches for the a value in the object that matches the key string given. Recursive.
Parameters
[in,out] obj If non-null, the object.
[in,out] key If non-null, the key.
[in,out] g_str If non-null, the string.
Returns
null if it fails, else the found value.
Author
Anthony Rios
Date
3/25/2016
Definition at line 53 of file mystrings.c.
References object_t::children, CountMem(), FindValue(), JsmnToString(), object_t::keys, and object_t::values.
Referenced by FindValue(), LoadLevel(), LoadMenu(), LoadMenuData(), ParsePresetAI(), ParseToPowerUp(), and Update().
 {
         int i, keys, objects;
         char *temp_str;
         keys = CountMem(obj->keys, sizeof(jsmntok_t));
         objects = CountMem(obj->children, sizeof(object_t));
         //Iterate through keys
         for(i = 0; i < keys; i++)
         {
                 temp_str = JsmnToString(&obj->keys[i], g_str);
                 if(!temp_str)
                         continue;
                 if(!strcmp(temp_str, key))
                 {
                         if(temp_str) free(temp_str);
                         return JsmnToString(&obj->values[i], g_str);
                 }
                 if(temp_str) free(temp_str);
         }
         //Iterate through children
         for(i = 0; i < objects; i++)
         {
                 if( (temp_str = FindValue(&obj->children[i], key, g_str)) != NULL)
                 {
                         return temp_str;
                 }
                 if(temp_str) free(temp_str);
         }
         return NULL;
 }
void JsmnToInt (jsmntok_t * token, char * str, int * dst)
Jsmn to int.
Parameters
[in,out] token If non-null, the token.
[in,out] str If non-null, the string.
[in,out] dst If non-null, destination for the value.
Author
Anthony Rios
Date
2/28/2016
Definition at line 84 of file mystrings.c.
References JsmnToString(), and StrToInt().
Referenced by LoadLevelData(), and ParseToEntity().
 {
         char *temp;
         temp = JsmnToString(token, str);
         *dst = StrToInt(temp);
         if(temp) free(temp);
 }
char* JsmnToString (jsmntok_t * token, char * g_str)
Jsmn to string.
Parameters
[in,out] token If non-null, the token.
[in,out] g_str If non-null, the global string.
Returns
null if it fails, else a char*.
Author
Anthony Rios
Date
1/30/2016
Definition at line 34 of file mystrings.c.
References ALLOC_STR, jsmntok_t::end, and jsmntok_t::start.
Referenced by FindKey(), FindValue(), JsmnToInt(), LoadGameData(), LoadLevel(), LoadLevelData(), LoadMenuData(), LoadPowerUpData(), ParseAI(), ParseComplexMember(), ParsePresetAI(), ParseToEntity(), ParseToObject(), ParseToStringArray(), ParseToVec2(), PrintObject(), SetAI_Action(), and UpdatePowerUpMenu().
 {
         int size = token->end - token->start;
         char *retVal;
         if(size < 0)
         {
                 return NULL;
         }
         retVal = ALLOC_STR(size+1);
         if(!retVal)
         {
                 printf("Could not allocate memory");
                 exit(-1);
         }
         strncpy( retVal, &g_str[token->start], size);
         retVal[size] = 0;
         return retVal;
 }
char** ParseToStringArray (object_t * object, char * str)
Definition at line 402 of file mystrings.c.
References CountMem(), and JsmnToString().
 {
         int i, size;
         char *temp;
         char **retVal;
         if(!object || !str)
                 return NULL;
         size = CountMem(object->values, sizeof(jsmntok_t));
         retVal = (char**) malloc(sizeof(char*)*(size+1));
         for(i = 0; i < size; i++)
         {
                 temp = JsmnToString(&object->values[i], str);
                 retVal[i] = temp;
         }
         retVal[size+1] = 0;
         return retVal;
 }
vec2_t* ParseToVec2 (object_t * object, char * str)
Definition at line 385 of file mystrings.c.
References JsmnToString(), StrToInt(), vec2_t::x, and vec2_t::y.
 {
         vec2_t *retVal;
         char *temp1, *temp2;
         retVal = (vec2_t*) malloc(sizeof(vec2_t));
         if(!retVal || !object || !str)
         {
                 return NULL;
         }
         temp1 = JsmnToString(&object->values[0], str);
         temp2 = JsmnToString(&object->values[1], str);
         retVal->x = StrToInt(temp1);
         retVal->y = StrToInt(temp2);
         free(temp1); free(temp2);
         return retVal;
 }
collision_type_t StrToCollisionType (char * str)
Converts a str to a collision type.
Parameters
[in,out] str If non-null, the string.
Returns
str as a collision_type_t.
Author
Anthony Rios
Date
3/29/2016
Definition at line 344 of file mystrings.c.
References COLLISION_TYPE_CLIP, and Collisions_str.
Referenced by ParseComplexMember().
 {
         int i;
         if(!str)
                 return 0;
         for(i = 0; i <= COLLISION_TYPE_CLIP; i++)
         {
                 if(!strcmp(Collisions_str[i], str))
                 {
                         return (collision_type_t)i;
                 }
         }
         return 0;
 }
entity_state_t StrToEntityState (char * str)
Converts a str to an entity state.
Parameters
[in,out] str If non-null, the string.
Returns
str as an entity_state_t.
Author
Anthony Rios
Date
3/29/2016
Definition at line 370 of file mystrings.c.
References COLLISION_TYPE_CLIP, and EntityStates_str.
Referenced by ParseComplexMember().
 {
         int i;
         if(!str)
                 return 0;
         for(i = 0; i <= COLLISION_TYPE_CLIP; i++)
         {
                 if(!strcmp(EntityStates_str[i], str))
                 {
                         return (entity_state_t)i;
                 }
         }
         return 0;
 }
GameState StrToGameState (char * str)
Converts a str to a game state.
Parameters
[in,out] str If non-null, the string.
Returns
str as a GameState.
Author
Anthony Rios
Date
3/29/2016
Definition at line 274 of file mystrings.c.
References CHOOSE, END, GAME_STATE_CHOOSE_STR, GAME_STATE_END_STR, GAME_STATE_GUESS_STR, GAME_STATE_PLAYING_STR, GAME_STATE_SPLASH_STR, GAME_STATE_START_STR, GUESS, PLAYING, SPLASH, and START.
Referenced by LoadMenu(), and LoadMenuData().
 {
         if(!str)
         {
                 return SPLASH;
         }
         else if(!strcmp(str, GAME_STATE_SPLASH_STR))
         {
                 return SPLASH;
         }
         else if(!strcmp(str, GAME_STATE_START_STR))
         {
                 return START;
         }
         else if(!strcmp(str, GAME_STATE_GUESS_STR))
         {
                 return GUESS;
         } else if(!strcmp(str, GAME_STATE_CHOOSE_STR))
         {
                 return CHOOSE;
         }
         else if(!strcmp(str, GAME_STATE_PLAYING_STR))
         {
                 return PLAYING;
         }
         if(!strcmp(str, GAME_STATE_END_STR))
         {
                 return END;
         }
         return SPLASH;
 }
int StrToHazard (char * str)
Converts a str to a hazard.
Parameters
[in,out] str If non-null, the string.
Returns
str as an int.
Author
Anthony Rios
Date
3/29/2016
Definition at line 317 of file mystrings.c.
References CountMem(), and Hazards_str.
Referenced by ParseComplexMember().
 {
         int i, length;
         if(!str)
                 return 0;
         length = CountMem(Hazards_str, sizeof(char*));
         for(i = 0; i < length; i++)
         {
                 if(!strcmp(str, Hazards_str[i]))
                 {
                         return (1 << i);
                 }
         }
         return 0;
 }
int StrToInt (char * str)
String to int.
Parameters
[in,out] str If non-null, the string.
Returns
An int.
Author
Anthony Rios
Date
2/28/2016
Definition at line 92 of file mystrings.c.
References CharToInt().
Referenced by JsmnToInt(), LoadLevel(), ParseAI(), ParseToVec2(), SetAI_Check(), and SetAI_Var().
 {
         int i, retVal, length, neg;
         if(str == NULL)
         {
                 return 0;
         }
         length = strlen(str);
         retVal = 0;
         neg = 0;
         if(str[0] == '-')
         {
                 i = 1;
                 neg = 1;
         } else
         {
                 i = 0;
         }
         for(i; i < length; i++)
         {
                 retVal += CharToInt(str[i])*(powf( 10, (length-i-1) ) );
         }
         if(neg)
         {
                 retVal *= -1;
         }
         return retVal;
 }
char* TypeFromJSON (jsmntype_t Type)
Type string from JSON string.
Parameters
Type The type.
Returns
null if it fails, else a char*.
Author
Anthony Rios
Date
1/30/2016
Definition at line 140 of file mystrings.c.
References JSMN_ARRAY, JSMN_OBJECT, JSMN_PRIMITIVE, JSMN_STRING, and JSMN_UNDEFINED.
 {
         switch(Type)
         {
         case(JSMN_UNDEFINED):
                 return "UNDEFINED";
         case(JSMN_OBJECT):
                 return "OBJECT";
         case(JSMN_ARRAY):
                 return "ARRAY";
         case(JSMN_STRING):
                 return "STRING";
         case(JSMN_PRIMITIVE):
                 return "PRIMITIVE";
         default:
                 return "UNKOWN";
         }
 }