Dumb-ways-to-memorize: dumb-ways-to-memorize/globals.h File Reference
globals.h File Reference
#include <jsmn.h>
Data Structures
struct vec2_t
struct KV_Pair_t
Macros
#define STRING_TYPE(X)
#define SIGN_BIT 0xF000
#define HAZARD_NULL 0x0
#define HAZARD_MAX (0x1 >> 31)
#define HAZARD_DAMAGE 10
#define HAZARD_STUN_FRAMES 10
#define ENTITIES_FILE_STR "Entities"
#define POWER_UPS_STR "PowerUps"
#define G_NAME_STR "Name"
#define LOC_NAME_STR "name"
#define FRAME_DELAY 13
#define PHYSICS_LIMITER 2
Typedefs
typedef unsigned int address_t
Enumerations
enum entity_state_t {
ENTITY_STATE_DEAD,
ENTITY_STATE_ALIVE,
ENTITY_STATE_OTHER
}
enum collision_type_t {
COLLISION_TYPE_STATIC,
COLLISION_TYPE_RAGDOLL,
COLLISION_TYPE_CLIP
}
enum menu_item_state_t {
MENU_ITEM_STATE_NULL,
MENU_ITEM_STATE_SELECTED = 0x1,
MENU_ITEM_STATE_NOT_SELECTED = 0x2,
MENU_ITEM_STATE_PICKED = 0x4,
MENU_ITEM_STATE_MAX = 0x8
}
enum animation_state_t {
ANIMATION_IDLE,
ANIMATION_WALK,
ANIMATION_JUMP,
ANIMATION_ATTACK,
ANIMATION_HIT,
ANIMATION_MAX = 20
}
enum GameState {
SPLASH = 0x1,
START = 0x2,
GUESS = 0x4,
CHOOSE = 0x8,
PLAYING = 0x10,
END = 0x20
}
Functions
void Vec2Add (vec2_t *A, vec2_t *B, vec2_t *C)
void Vec2Subtract (vec2_t *First, vec2_t *Second, vec2_t *C)
void Vec2MultiplyScalar (vec2_t *A, int B, vec2_t *C)
int LargestDivisor (int num)
GameState StrToGameState (char *str)
int StrToMenuType (char *str)
int StrToHazard (char *str)
collision_type_t StrToCollisionType (char *str)
entity_state_t StrToEntityState (char *str)
int SelectLevels ()
int LoadSelectedLevel (int level)
void RandomizeSelectedLevels ()
int CountMem (void *src, int size_type)
int AllocateDynamic (void **dst, void *src, int size_type, int size)
int CompareMemToMemArray (void *mem, void *mem_array, int size_type, int size_array)
vec2_t * ParseToVec2 (struct object_s *object, char *str)
char ** ParseToStringArray (struct object_s *object, char *str)
Variables
vec2_t gZeroPos
GameState gGameState
char ** Hazards_str
char * gEntitiesFile
char * Collisions_str []
char * EntityStates_str []
char * gPowerUpsFile
vec2_t * mousePos
int * keyPower
char ** gSelectedPowerUps
char ** gUsedPowerUps
char * gCurrentPowerUpName
char ** gLevels
char ** gSelectedLevels
void * gWorld
void * gMouse
int gPlayerLives
int gLevelsPerGame
int gScreenWidth
int gScreenHeight
unsigned int gCurrentTime
vec2_t gGravity
int exitRequest
jsmn_parser gParser
jsmntok_t * gGameTokens
struct object_s * gGameObject
jsmntok_t * gEntityTokens
struct object_s * gEntityObject
jsmntok_t * gLevelTokens
struct object_s * gLevelObject
char * gGameData
char * gEntityData
char * gLevelData
Macro Definition Documentation
#define ENTITIES_FILE_STR "Entities"
Definition at line 106 of file globals.h.
Referenced by LoadGameData().
#define FRAME_DELAY 13
Definition at line 135 of file globals.h.
Referenced by AttackAI(), InitPlayer(), JumpAI(), MoveAI(), NothingAI(), Run(), ThinkGeneric(), TouchGeneric(), TouchPlayer(), and WalkAI().
#define G_NAME_STR "Name"
Definition at line 133 of file globals.h.
Referenced by LoadLevel().
#define HAZARD_DAMAGE 10
Definition at line 100 of file globals.h.
Referenced by TouchGeneric(), and TouchPlayer().
#define HAZARD_MAX (0x1 >> 31)
Definition at line 99 of file globals.h.
#define HAZARD_NULL 0x0
Definition at line 98 of file globals.h.
#define HAZARD_STUN_FRAMES 10
Definition at line 101 of file globals.h.
Referenced by TouchGeneric(), and TouchPlayer().
#define LOC_NAME_STR "name"
Definition at line 134 of file globals.h.
#define PHYSICS_LIMITER 2
Definition at line 136 of file globals.h.
Referenced by RunPhysics().
#define POWER_UPS_STR "PowerUps"
Definition at line 114 of file globals.h.
Referenced by LoadGameData().
#define SIGN_BIT 0xF000
Definition at line 16 of file globals.h.
#define STRING_TYPE (X)
Value:
(X == sizeof(char) ? "Char"  \
                                                : (X == sizeof(int) ? "Int"  \
                                                : (X == sizeof(jsmntok_t) ? "Jsmn" \
                                                : "Unkown" ) ) )
Returns string of the type of size X
Definition at line 6 of file globals.h.
Typedef Documentation
typedef unsigned int address_t
Definition at line 28 of file globals.h.
Enumeration Type Documentation
enum animation_state_t
Defines an enum for animation states in mSprites array
Enumerator
ANIMATION_IDLE
An enum constant representing the idle animation
ANIMATION_WALK
An enum constant representing the walk animation
ANIMATION_JUMP
An enum constant representing the jump animation
ANIMATION_ATTACK
An enum constant representing the attack animation
ANIMATION_HIT
An enum constant representing the hit animation
ANIMATION_MAX
An enum constant representing the maximum animations
Definition at line 71 of file globals.h.
 {
enum collision_type_t
Defines the enum which are the collision types for the physics engine
Enumerator
COLLISION_TYPE_STATIC
An enum constant representing the collision type static - which means it collides, but doesn't move
COLLISION_TYPE_RAGDOLL
An enum constant representing the collision type ragdoll - which collides + moves
COLLISION_TYPE_CLIP
An enum constant representing the collision type clip - which means it doesn't collide , but moves. Should be used for particle entities (maybe)
Definition at line 53 of file globals.h.
 {
enum entity_state_t
Defines the enum relating to entity states
Enumerator
ENTITY_STATE_DEAD
An enum constant representing the entity state dead
ENTITY_STATE_ALIVE
An enum constant representing the entity state alive option
ENTITY_STATE_OTHER
An enum constant representing the entity state other, which is used for non-health based entities
Definition at line 45 of file globals.h.
 {
enum GameState
Defines the enum for the game states
Enumerator
SPLASH
An enum constant representing the splash screen game state
START
An enum constant representing the start screen game state
GUESS
An enum constant representing the first time the player chooses the power_ups
CHOOSE
An enum constant representing the state in which the player selects a power_up from the chosen power ups in guess
PLAYING
An enum constant representing the playing game state, which is consistent of the level, enemy entities, and the player
END
An enum constant representing the player has chosen to quit the game
Definition at line 83 of file globals.h.
enum menu_item_state_t
Defines the enum for menu item states
Enumerator
MENU_ITEM_STATE_NULL
MENU_ITEM_STATE_SELECTED
An enum constant representing the menu item state selected - which means the player is hovering over this now
MENU_ITEM_STATE_NOT_SELECTED
An enum constant representing the menu item state not selected
MENU_ITEM_STATE_PICKED
An enum constant representing the menu item state picked - which is a option that is checked
MENU_ITEM_STATE_MAX
Definition at line 61 of file globals.h.
 {
Function Documentation
int AllocateDynamic (void ** dst, void * src, int size_type, int size)
Allocate memory and copy over src into it. Adds Null to end. Returns NULL on size 0
Parameters
[in,out] dst If non-null, destination for the allocation.
[in,out] src If non-null, source for the adding.
size_type Size of the type.
size The size.
Returns
0 on success, -1 on error.
Author
Anthony Rios
Date
2/1/2016
Definition at line 66 of file mymath.c.
Referenced by CopyObjectToObjectArray(), and ParseToObject().
 {
         int offset = size_type/sizeof(int);
         if(!dst) return -1;
         *dst = realloc(*dst, size_type*(size+1));
         if(!*dst) return -1;
         src ? memcpy((int*)(*dst)+(size-1)*offset, src, size_type) : memset((int*)(*dst)+(size-1)*offset, 0, size_type);
         memset((int*)(*dst)+(size)*offset, 0, size_type);
         return 0;
 }
int CompareMemToMemArray (void * mem, void * mem_array, int size_type, int size_array)
Compare memory to memory array.
Parameters
[in,out] mem If non-null, the memory.
[in,out] mem_array If non-null, array of memories.
size_type Size of type, via sizeof() function.
size_array Size of Array.
Returns
0 if equal, -1 if not.
Author
Anthony Rios
Date
1/31/2016
Definition at line 77 of file mymath.c.
Referenced by RandomizeSelectedLevels(), and SelectLevels().
 {
         int i, offset;
         int *memory = (int*) mem_array;
         offset = size_type;
         for(i = 0; i < size_array; i++)
         {
                 if(!memcmp(mem, memory, size_type))
                 {
                         return 0;
                 }
                 memory += offset;
         }
         return -1;
 }
int CountMem (void * src, int size_type)
Counts the memory of type size_type, given that the final address is null.
Parameters
[in,out] src If non-null, source of memory.
size_type Size of the type.
Returns
The total number of memory, if src is null 0 is returned.
Author
Anthony Rios
Date
2/1/2016
Definition at line 51 of file mymath.c.
Referenced by CopyObjectToObjectArray(), CountObjectChildren(), CountObjectMembers(), DoPlayerThink(), FindKey(), FindMenuItem(), FindPower(), FindValue(), IncrementFrame(), LoadEntityData(), LoadLevel(), LoadLevelData(), LoadMenu(), LoadMenuData(), LoadPowerUpData(), ParseAI(), ParsePresetAI(), ParseToEntity(), ParseToStringArray(), PrintObject(), ProcessMenuItemsByType(), RandomizeSelectedLevels(), StrToHazard(), TouchGeneric(), TouchGoal(), TouchPlayer(), UpdatePowerSelectMenu(), UpdatePowerUpMenu(), and UpdateVerticalMenu().
 {
         int i, offset;
         int *source = (int*)src;
         if(source == NULL)
                 return 0;
         i = 0; offset = size_type/sizeof(int);
         while( *(source) )
         {
                 source += offset;
                 i++;
         }
         return i;
 }
int LargestDivisor (int num)
Definition at line 5 of file mymath.c.
Referenced by ProcessMenuItemsByType().
 {
         int i, root, hit;
         hit = 0;
         root = num>>1;
         for(i = 0; i < root; i++)
         {
                 if(!num%i)
                 {
                         hit = i;
                 }
         }
         return hit;
 }
int LoadSelectedLevel (int level)
Loads selected level.
Parameters
level The level.
Returns
The selected level.
See also
LoadLevel , in parselevel.c
Author
Anthony Rios
Date
3/29/2016
Definition at line 390 of file game.c.
References ConvertFileToUseable(), gLevelData, gLevelObject, gSelectedLevels, LoadLevel(), and ParseToObject().
Referenced by UpdatePowerSelectMenu().
 {
         if(!gSelectedLevels)
         {
                 printf("Levels not Selected \n");
                 return -1;
         }
         if(!gSelectedLevels[level])
         {
                 printf("Level %d not found \n", level);
                 return -1;
         }
         ConvertFileToUseable(gSelectedLevels[level], &gParser, &gLevelData, &gLevelTokens);
         if(!gLevelData || !gLevelTokens)
         {
                 printf("Unable to parse level %s \n", gSelectedLevels[level]);
         }
         gLevelObject = ParseToObject(gLevelTokens, gLevelData);
         if(!gLevelObject)
         {
                 printf("Unable to parse level %s to object \n", gSelectedLevels[level]);
         }
         if(LoadLevel(gLevelObject, gLevelData))
         {
                 perror("Unable to Load level \n");
                 return -1;
         }
         return 0;
 }
char** ParseToStringArray (struct object_s * object, char * str)
Parse obj/data to string array.
Parameters
[in,out] object If non-null, the object.
[in,out] str If non-null, the string.
Returns
null if it fails, else a handle to a char.
Author
Anthony Rios
Date
3/29/2016
Referenced by LoadEntityData(), and LoadLevel().
vec2_t* ParseToVec2 (struct object_s * object, char * str)
Parse given obj/str to vector 2.
Parameters
[in,out] object If non-null, the object.
[in,out] str If non-null, the string.
Returns
null if it fails, else a pointer to a vec2_t.
Author
Anthony Rios
Date
3/29/2016
Referenced by LoadGameData(), LoadLevel(), ParseToEntity(), and SetAI_Action().
void RandomizeSelectedLevels ()
Randomize selected levels.
Author
Anthony Rios
Date
2/19/2016
Definition at line 343 of file game.c.
References CompareMemToMemArray(), CountMem(), gLevels, gLevelsPerGame, and gSelectedLevels.
 {
         int i, rand_i, *no_repeats;
         char **slevel_copy;
         if (CountMem(gLevels, sizeof(char*)) < gLevelsPerGame)
         {
                 printf("Levels less than min, Easy Mode - No Rand");
                 return;
         }
         //Get a copy of gSelected
         slevel_copy = (char**) malloc(sizeof(char*)*(gLevelsPerGame+1));
         memcpy(slevel_copy, gSelectedLevels, sizeof(char*)*gLevelsPerGame);
         slevel_copy[gLevelsPerGame] = 0;
         //No Repeats
         no_repeats = (int*) malloc(sizeof(int)*gLevelsPerGame+1);
         memset(no_repeats, 0, sizeof(int)*(gLevelsPerGame+1));
         //Randomize
         for(i = 0; gSelectedLevels[i]; i++)
         {
                 rand_i = rand()%gLevelsPerGame;
                 while(!CompareMemToMemArray(&rand_i, no_repeats, sizeof(int), gLevelsPerGame ))
                 {
                         rand_i = rand()%gLevelsPerGame;
                 }
                 no_repeats[i] = rand_i;
                 gSelectedLevels[i] = slevel_copy[rand_i];
         }
         free(no_repeats);
         free(slevel_copy);
 }
int SelectLevels ()
Select the levels randomly from the available levels, stores in gSelectedLevels.
Returns
0 on success, -1 on error
Author
Anthony Rios
Date
1/31/2016
Definition at line 297 of file game.c.
References CompareMemToMemArray(), gLevels, gLevelsPerGame, and gSelectedLevels.
Referenced by Setup().
 {
         int i, rand_i, *no_repeats, type_i;
         int levels = 0;
         //Count
         while(gLevels[levels])
         {
                 levels++;
         }
         type_i = sizeof(int);
         //Alloc
         gSelectedLevels = (char**) malloc(sizeof(char*)*levels+1);
         no_repeats = (int*) malloc(sizeof(int)*(levels+1));
         if(!gSelectedLevels) return -1;
         if(!no_repeats) return -1;
         //Select
         memset(no_repeats, 0, sizeof(int));
         for (i = 0; i < gLevelsPerGame; i++)
         {
                 rand_i = rand()%levels;
                 if(i >= levels)
                 {
                         break;
                 }
                 while(!CompareMemToMemArray(&rand_i, no_repeats, type_i, levels ))
                 {
                         rand_i = rand()%levels;
                 }
                 no_repeats[i] = rand_i;
                 gSelectedLevels[i] = gLevels[rand_i];
         }
         gSelectedLevels[i] = NULL;
         free(no_repeats);
         return 0;
 }
collision_type_t StrToCollisionType (char * str)
Converts a string into a entity collision type
Converts a str to a collision type.
Parameters
[in,out] str If non-null, the string.
Returns
str as a collision_type_t.
Author
Anthony Rios
Date
3/29/2016
Definition at line 344 of file mystrings.c.
References COLLISION_TYPE_CLIP, and Collisions_str.
Referenced by ParseComplexMember().
 {
         int i;
         if(!str)
                 return 0;
         for(i = 0; i <= COLLISION_TYPE_CLIP; i++)
         {
                 if(!strcmp(Collisions_str[i], str))
                 {
                         return (collision_type_t)i;
                 }
         }
         return 0;
 }
entity_state_t StrToEntityState (char * str)
Converts a string into an entity state
Converts a str to an entity state.
Parameters
[in,out] str If non-null, the string.
Returns
str as an entity_state_t.
Author
Anthony Rios
Date
3/29/2016
Definition at line 370 of file mystrings.c.
References COLLISION_TYPE_CLIP, and EntityStates_str.
Referenced by ParseComplexMember().
 {
         int i;
         if(!str)
                 return 0;
         for(i = 0; i <= COLLISION_TYPE_CLIP; i++)
         {
                 if(!strcmp(EntityStates_str[i], str))
                 {
                         return (entity_state_t)i;
                 }
         }
         return 0;
 }
GameState StrToGameState (char * str)
Converts a string into a game state
Converts a str to a game state.
Parameters
[in,out] str If non-null, the string.
Returns
str as a GameState.
Author
Anthony Rios
Date
3/29/2016
Definition at line 274 of file mystrings.c.
References CHOOSE, END, GAME_STATE_CHOOSE_STR, GAME_STATE_END_STR, GAME_STATE_GUESS_STR, GAME_STATE_PLAYING_STR, GAME_STATE_SPLASH_STR, GAME_STATE_START_STR, GUESS, PLAYING, SPLASH, and START.
Referenced by LoadMenu(), and LoadMenuData().
 {
         if(!str)
         {
                 return SPLASH;
         }
         else if(!strcmp(str, GAME_STATE_SPLASH_STR))
         {
                 return SPLASH;
         }
         else if(!strcmp(str, GAME_STATE_START_STR))
         {
                 return START;
         }
         else if(!strcmp(str, GAME_STATE_GUESS_STR))
         {
                 return GUESS;
         } else if(!strcmp(str, GAME_STATE_CHOOSE_STR))
         {
                 return CHOOSE;
         }
         else if(!strcmp(str, GAME_STATE_PLAYING_STR))
         {
                 return PLAYING;
         }
         if(!strcmp(str, GAME_STATE_END_STR))
         {
                 return END;
         }
         return SPLASH;
 }
int StrToHazard (char * str)
Converts a string into a hazard, using the parsed hazards_str for comparison
Converts a str to a hazard.
Parameters
[in,out] str If non-null, the string.
Returns
str as an int.
Author
Anthony Rios
Date
3/29/2016
Definition at line 317 of file mystrings.c.
References CountMem(), and Hazards_str.
Referenced by ParseComplexMember().
 {
         int i, length;
         if(!str)
                 return 0;
         length = CountMem(Hazards_str, sizeof(char*));
         for(i = 0; i < length; i++)
         {
                 if(!strcmp(str, Hazards_str[i]))
                 {
                         return (1 << i);
                 }
         }
         return 0;
 }
int StrToMenuType (char * str)
Converts a string into a menu type
Definition at line 697 of file menu.c.
References MENU_TYPE_CHOOSE, MENU_TYPE_GRID, MENU_TYPE_H, MENU_TYPE_NULL, MENU_TYPE_POWER, MENU_TYPE_STR_CHOOSE, MENU_TYPE_STR_GRID, MENU_TYPE_STR_H, MENU_TYPE_STR_POWER, MENU_TYPE_STR_V, and MENU_TYPE_V.
Referenced by LoadMenu().
 {
         if(!strcmp(str, MENU_TYPE_STR_H))
         {
                 return MENU_TYPE_H;
         }
         if(!strcmp(str, MENU_TYPE_STR_V))
         {
                 return MENU_TYPE_V;
         }
         if(!strcmp(str, MENU_TYPE_STR_GRID))
         {
                 return MENU_TYPE_GRID;
         }
         if(!strcmp(str, MENU_TYPE_STR_POWER))
         {
                 return MENU_TYPE_POWER;
         }
         if(!strcmp(str, MENU_TYPE_STR_CHOOSE))
         {
                 return MENU_TYPE_CHOOSE;
         }
         return MENU_TYPE_NULL;
 }
void Vec2Add (vec2_t * A, vec2_t * B, vec2_t * C)
Definition at line 20 of file mymath.c.
References vec2_t::x, and vec2_t::y.
Referenced by DoCollision(), JumpAI(), MoveAI(), RunPhysics(), Spawn(), and WalkAI().
 {
         if(!A || !B || !C)
         {
                 return;
         }
         C->x = A->x + B->x;
         C->y = A->y + B->y;
 }
void Vec2MultiplyScalar (vec2_t * A, int B, vec2_t * C)
Definition at line 41 of file mymath.c.
References vec2_t::x, and vec2_t::y.
Referenced by JumpAI(), MoveAI(), and WalkAI().
 {
         if(!A || !C)
         {
                 return;
         }
         (*C).x = A->x * B;
         (*C).y = A->y * B;
 }
void Vec2Subtract (vec2_t * First, vec2_t * Second, vec2_t * C)
Definition at line 31 of file mymath.c.
References vec2_t::x, and vec2_t::y.
 {
         if(!First || !Second || !C)
         {
                 return;
         }
         C->x = First->x - Second->x;
         C->y = First->y - Second->y;
 }
Variable Documentation
char* Collisions_str[]
The collisions type strings for parsing
Definition at line 14 of file entity.c.
Referenced by StrToCollisionType().
char* EntityStates_str[]
The entity state strings for parsing
Definition at line 15 of file entity.c.
Referenced by StrToEntityState().
int exitRequest
The integer to be changed to exit
Definition at line 22 of file game.c.
Referenced by DrawChoose(), DrawGuess(), DrawStart(), InitPlayer(), Poll(), Run(), and Update().
char* gCurrentPowerUpName
The current power up name
Definition at line 43 of file game.c.
Referenced by UpdatePowerSelectMenu().
unsigned int gCurrentTime
The current time , updated from last update call
Definition at line 50 of file game.c.
Referenced by InitPlayer(), JumpAI(), MoveAI(), NothingAI(), Run(), RunEntities(), ThinkGeneric(), ThinkPlayer(), Update(), and WalkAI().
char* gEntitiesFile
The name of the entities file
Definition at line 39 of file game.c.
Referenced by LoadEntityData(), and LoadGameData().
char* gEntityData
The current parsed string of the entity file
Definition at line 37 of file game.c.
Referenced by LoadEntityData().
struct object_s* gEntityObject
The entity object
Definition at line 34 of file game.c.
Referenced by LoadEntityData().
jsmntok_t* gEntityTokens
The entity jsmn tokens
Definition at line 31 of file game.c.
char* gGameData
Game Data File - holding the contents of file via string
Definition at line 36 of file game.c.
Referenced by LoadEntityData(), LoadGameData(), LoadLevelData(), LoadMenuData(), LoadPowerUpData(), Update(), and UpdatePowerUpMenu().
struct object_s* gGameObject
The game object
Definition at line 33 of file game.c.
Referenced by LoadEntityData(), LoadGameData(), LoadLevelData(), LoadMenuData(), LoadPowerUpData(), Update(), and UpdatePowerUpMenu().
GameState gGameState
State of the game
Definition at line 44 of file game.c.
Referenced by Draw(), ThinkPlayer(), TouchGoal(), Update(), UpdatePowerSelectMenu(), UpdatePowerUpMenu(), and UpdateVerticalMenu().
jsmntok_t* gGameTokens
Tokens for GameData
Definition at line 30 of file game.c.
vec2_t gGravity
The gravity which affects all the assets
Definition at line 7 of file dumb_physics.c.
char* gLevelData
Information describing the current level
Definition at line 38 of file game.c.
Referenced by LoadSelectedLevel().
struct object_s* gLevelObject
The current level object
Definition at line 35 of file game.c.
Referenced by LoadSelectedLevel().
char** gLevels
The level names
Definition at line 26 of file game.c.
Referenced by LoadLevelData(), RandomizeSelectedLevels(), and SelectLevels().
int gLevelsPerGame
The levels per game
Definition at line 24 of file game.c.
Referenced by LoadLevelData(), RandomizeSelectedLevels(), SelectLevels(), and UpdatePowerUpMenu().
jsmntok_t* gLevelTokens
The level jsmn tokens
Definition at line 32 of file game.c.
void* gMouse
jsmn_parser gParser
The global jsmn parser
Definition at line 25 of file game.c.
int gPlayerLives
The lives of the player
Definition at line 10 of file player.c.
Referenced by DecrementPlayerLives(), InitPlayer(), and ThinkPlayer().
char* gPowerUpsFile
The name of the power ups file
Definition at line 40 of file game.c.
Referenced by LoadGameData(), and LoadPowerUpData().
int gScreenHeight
Te set Height of the screen
Definition at line 17 of file graphics.c.
Referenced by ApplyBounds(), InitGraphics(), LoadGameData(), and ProcessMenuItemsByType().
int gScreenWidth
The set Width of the screen
Definition at line 16 of file graphics.c.
Referenced by ApplyBounds(), InitGraphics(), LoadGameData(), and ProcessMenuItemsByType().
char** gSelectedLevels
The selected levels to load
Definition at line 27 of file game.c.
Referenced by LoadSelectedLevel(), RandomizeSelectedLevels(), and SelectLevels().
char** gSelectedPowerUps
The power ups the player selects
Definition at line 28 of file game.c.
Referenced by LoadMenu(), TouchGoal(), UpdatePowerSelectMenu(), and UpdatePowerUpMenu().
char** gUsedPowerUps
The used power ups for this game run
Definition at line 29 of file game.c.
Referenced by TouchGoal(), UpdatePowerSelectMenu(), and UpdatePowerUpMenu().
void* gWorld
vec2_t gZeroPos
Definition at line 46 of file game.c.
Referenced by InitPlayer().
char** Hazards_str
The hazards string array which is defined in the gamedata file
Definition at line 13 of file entity.c.
Referenced by LoadEntityData(), and StrToHazard().
int* keyPower
The key press related to using the power
Definition at line 18 of file parsepowerup.c.
Referenced by CallInfo(), and ParseToPowerUp().
vec2_t* mousePos
The mouse position
Definition at line 17 of file parsepowerup.c.