Dumb-ways-to-memorize: dumb-ways-to-memorize/player.c File Reference
player.c File Reference
#include "globals.h"
#include "parsepowerup.h"
#include "entity.h"
#include "player.h"
#include "parselevel.h"
#include <stdio.h>
Functions
void InitPlayer ()
void DecrementPlayerLives ()
Variables
char * gPlayerName = PLAYER_NAME
entity_t * gPlayer = NULL
int gPlayerLives = 0
Function Documentation
void DecrementPlayerLives ()
Definition at line 40 of file player.c.
References gPlayerLives.
 {
         gPlayerLives--;
 }
void InitPlayer ()
Initialize the player entity and variables thereof, also used to reset player.
Author
Anthony Rios
Date
3/30/2016
Definition at line 12 of file player.c.
References DrawGeneric(), exitRequest, FindCachedEntity(), FRAME_DELAY, gCurrentLevel, gCurrentTime, gPlayer, gPlayerLives, gPowerUps, gZeroPos, InitNewEntity(), PLAYER_LIVES, ThinkPlayer(), TouchPlayer(), and UsePower().
Referenced by UpdatePowerSelectMenu().
 {
         if(!gPlayer)
         {
                 gPlayer = InitNewEntity();
         }
         if(!gPlayer)
         {
                 printf("Could not Init Player");
                 exitRequest = 1;
                 return;
         }
         memcpy(gPlayer,FindCachedEntity("Player"), sizeof(entity_t));
         if(!gPlayerLives)
         {
                 PLAYER_LIVES;
         }
         gPlayer->Draw = DrawGeneric;
         gPlayer->Think = ThinkPlayer;
         gPlayer->Touch = TouchPlayer;
         gPlayer->PowerUp = gPowerUps ? UsePower : NULL;
         gPlayer->mPosition = gCurrentLevel ? gCurrentLevel->mSpawnPoint : gZeroPos;
         gPlayer->mHealth = 100;
         gPlayer->mWeight = 1;
         gPlayer->mNextThink = gCurrentTime + 2*FRAME_DELAY;
 }
Variable Documentation
entity_t* gPlayer = NULL
The player entity
Definition at line 9 of file player.c.
Referenced by CallInfo(), FreeNonPlayerEntities(), InitPlayer(), ThinkEnemy(), ThinkPlayer(), TouchGoal(), UpdateInfinite(), and UpdateNormal().
int gPlayerLives = 0
The lives of the player
Definition at line 10 of file player.c.
Referenced by DecrementPlayerLives(), InitPlayer(), and ThinkPlayer().
char* gPlayerName = PLAYER_NAME
The name of the player
Definition at line 8 of file player.c.