Dumb-ways-to-memorize: dumb-ways-to-memorize/graphics.h File Reference
graphics.h File Reference
#include <SDL.h>
#include "globals.h"
Data Structures
struct Frame
struct sprite_t
Macros
#define GAME_NAME "Dumb Ways to Memorize"
#define SCREEN_STRING "Screen Dimensions"
#define SCREEN_RES_W 1280
#define SCREEN_RES_H 720
#define MAX_SPRITES 500
#define MAX_ANIMATIONS 20
Functions
int InitGraphics ()
void ShutdownGraphics ()
Frame * LoadAnimation (int frame_width, int frame_height, int width, int height)
sprite_t * FindSprite (const char *name, int *position)
sprite_t * FindFreeSprite (int *position)
sprite_t * LoadSprite (const char *name, int flags)
int DrawSprite (sprite_t *sprite, int *frame, vec2_t *position, SDL_Renderer *renderer)
void FreeSprite (sprite_t *sprite)
void IncrementFrame (sprite_t *sprite)
void SDL_SetRect (SDL_Rect *rect, int x, int y, int w, int h)
Variables
sprite_t * gSprites
int gLastSprite
SDL_Window * gWindow
SDL_Renderer * gRenderer
SDL_Surface * gRedSurface
SDL_Texture * gRedTexture
SDL_Renderer * gRedRenderer
Macro Definition Documentation
#define GAME_NAME "Dumb Ways to Memorize"
Definition at line 7 of file graphics.h.
Referenced by InitGraphics().
#define MAX_ANIMATIONS 20
Definition at line 12 of file graphics.h.
Referenced by ParseToEntity().
#define MAX_SPRITES 500
Definition at line 11 of file graphics.h.
Referenced by FindFreeSprite(), FindSprite(), InitGraphics(), LoadSprite(), and ShutdownGraphics().
#define SCREEN_RES_H 720
Definition at line 10 of file graphics.h.
Referenced by InitGraphics(), and ProcessMenuItemsByType().
#define SCREEN_RES_W 1280
Definition at line 9 of file graphics.h.
Referenced by InitGraphics(), and ProcessMenuItemsByType().
#define SCREEN_STRING "Screen Dimensions"
Definition at line 8 of file graphics.h.
Referenced by LoadGameData().
Function Documentation
int DrawSprite (sprite_t * sprite, int * frame, vec2_t * position, SDL_Renderer * renderer)
Draw the sprite. If mCurrentFrame not set, draws the first frame (0,0). If no position given, will draw as if was background.
Parameters
[in,out] sprite If non-null, the sprite.
[in,out] frame If non-null, the frame number to draw.
[in,out] position If non-null, the position.
[in,out] renderer If non-null, the renderer.
Returns
0 if good, -1 if failure
Author
Anthony Rios
Date
3/16/2016
Definition at line 152 of file graphics.c.
References SDL_SetRect(), vec2_t::x, and vec2_t::y.
Referenced by DrawGeneric(), DrawLevel(), DrawMenuByNum(), DrawMenuByState(), and DrawSplash().
 {
         SDL_Rect src, dst;
         int zero = 0;
         if(!sprite)
         {
                 printf("Null sprite given \n");
                 return -1;
         }
         if(!frame)
         {
                 frame = &zero;
         }
         if( *frame >= sprite->mFrames )
         {
                 *frame = 0;
         }
         SDL_SetRect(&src, sprite->mAnimations[*frame].Position.x, sprite->mAnimations[*frame].Position.y, sprite->mSize.x, sprite->mSize.y);
         *frame = *frame+1;
         if(!position)
         {
                 SDL_SetRect(&dst, 0, 0, 0, 0);
                 SDL_GetRendererOutputSize(renderer, &dst.w, &dst.h);
         } else {
                 SDL_SetRect(&dst, position->x, position->y, sprite->mSize.x, sprite->mSize.y);
         }
         if( SDL_RenderCopy(renderer, sprite->mTexture, &src, &dst) )
         {
                 printf("Could not draw sprite %s : %s", sprite->name, SDL_GetError());
         }
         return 0;
 }
sprite_t* FindFreeSprite (int * position)
Searches for the first free sprite in sprite system memory.
Parameters
[in,out] position If non-null, the position.
Returns
null if it fails, else the found free sprite.
Author
Anthony Rios
Date
3/16/2016
Definition at line 226 of file graphics.c.
References gLastSprite, gSprites, and MAX_SPRITES.
Referenced by LoadSprite().
 {
         int i;
         for(i = gLastSprite; i < MAX_SPRITES; i++)
         {
                 if(gSprites[i].refCount == 0)
                 {
                         return &gSprites[i];
                 }
         }
         for(i = 0; i < gLastSprite; i++)
         {
                 if(gSprites[i].refCount == 0)
                 {
                         return &gSprites[i];
                 }
         }
         return NULL;
 }
sprite_t* FindSprite (const char * name, int * position)
Searches for the first sprite.
Parameters
name The name of the sprite file.
[in,out] position If non-null, the position.
Returns
null if it fails, else the found sprite.
Author
Anthony Rios
Date
3/16/2016
Definition at line 209 of file graphics.c.
References gSprites, and MAX_SPRITES.
Referenced by FreeSprite(), and LoadSprite().
 {
         int i;
         for(i = 0; i < MAX_SPRITES; i++)
         {
                 if(gSprites[i].refCount == 0)
                         continue;
                 if(!strcmp(gSprites[i].name, name))
                 {
                         if(position)
                                 *position = i;
                         return &gSprites[i];
                 }
         }
         return NULL;
 }
void FreeSprite (sprite_t * sprite)
Free the sprite memory, if recfcount - 1 > 0 nothing happens.
Parameters
[in,out] sprite If non-null, the sprite.
Author
Anthony Rios
Date
3/16/2016
Definition at line 246 of file graphics.c.
References FindSprite(), and gSprites.
Referenced by ShutdownGraphics().
 {
         int position;
         if(sprite == FindSprite(sprite->name, &position))
         {
                 sprite->refCount--;
                 if(sprite->refCount > 0)
                         return;
         }
         SDL_DestroyTexture(sprite->mTexture);
         free(sprite->name);
         memset(&gSprites[position], 0, sizeof(sprite_t) );
 }
void IncrementFrame (sprite_t * sprite)
Definition at line 262 of file graphics.c.
References CountMem().
 {
         int frames;
         if(!sprite)
         {
                 return;
         }
         frames = CountMem(&sprite->mAnimations[0], sizeof(Frame));
         if(!frames)
         {
                 return;
         }
 }
int InitGraphics ()
Init graphics system. Calls SDL_Init and allocates memory for the sprites.
Returns
0 if good, -1 if failure.
Author
Anthony Rios
Date
3/16/2016
Definition at line 19 of file graphics.c.
References GAME_NAME, gLastSprite, gRedRenderer, gRedSurface, gRedTexture, gRenderer, gScreenHeight, gScreenWidth, gSprites, gWindow, MAX_SPRITES, SCREEN_RES_H, SCREEN_RES_W, and ShutdownGraphics().
Referenced by Setup().
 {
         Uint32 flags = 0;
         SDL_DisplayMode current;
         if(SDL_Init(SDL_INIT_EVERYTHING))
         {
                 printf("SDL can't initialize : %s", SDL_GetError());
                 exit(-1);
         }
         if(SDL_GetDisplayMode(0,0,&current))
         {
                 printf("No video mode: %s", SDL_GetError());
                 exit(-1);
         }
         //Create Window based on either default or set screenWidth / Height
         if(gScreenHeight && gScreenWidth)
         {
                 if( (gWindow = SDL_CreateWindow(GAME_NAME, SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, gScreenWidth, gScreenHeight, flags )) == NULL )
                 {
                         printf("Can't create window %s", SDL_GetError());
                         exit(-1);
                 }
         } else {
                 if( (gWindow = SDL_CreateWindow(GAME_NAME, SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, SCREEN_RES_W, SCREEN_RES_H, flags )) == NULL )
                 {
                         printf("Can't create window %s", SDL_GetError());
                         exit(-1);
                 }
                 gScreenHeight = SCREEN_RES_H;
                 gScreenWidth = SCREEN_RES_W;
         }
         //Main Rendering Context
         SDL_SetWindowTitle(gWindow, "Dumb Ways to Memorize");
         if( (gRenderer = SDL_CreateRenderer(gWindow, -1, flags)) == NULL)
         {
                 printf("Can't create renderer %s ", SDL_GetError());
                 exit(-1);
         }
         //Red Renderer
         if ( (gRedSurface = SDL_CreateRGBSurface(0,gScreenWidth,gScreenHeight,32,0,0,0,0)) == NULL)
         {
                 printf("Can't create red surface : %s \n", SDL_GetError());
         }
         if( (gRedRenderer = SDL_CreateSoftwareRenderer(gRedSurface)) == NULL)
         {
                 printf("Can't create red renderer : %s \n", SDL_GetError());
         }
         if( SDL_SetRenderDrawColor(gRedRenderer, 0xFF, 0, 0, 0xFF) )
         {
                 printf("Can't set red renderer : %s \n", SDL_GetError());
         }
         SDL_RenderClear(gRedRenderer);
         if( (gRedTexture = SDL_CreateTextureFromSurface(gRenderer, gRedSurface)) == NULL)
         {
                 printf("Can't create red texture : %s \n", SDL_GetError());
         }
         gSprites = (sprite_t*) malloc(sizeof(sprite_t)*MAX_SPRITES);
         if(!gSprites)
         {
                 printf("Could not allocate sprites");
                 return -1;
         }
         memset(gSprites, 0, sizeof(sprite_t)*MAX_SPRITES);
         gLastSprite = 0;
         atexit(SDL_Quit);
         atexit(ShutdownGraphics);
         return 0;
 }
Frame* LoadAnimation (int frame_width, int frame_height, int width, int height)
Loads an animation based on frame_width & frame_height.
Parameters
frame_width Width of the frame.
frame_height Height of the frame.
width The width.
height The height.
Returns
null if it fails, else the animation.
Author
Anthony Rios
Date
3/16/2016
Definition at line 190 of file graphics.c.
References Frame::Position, vec2_t::x, and vec2_t::y.
Referenced by ParseToEntity().
 {
         Frame *retVal;
         int i,j, rows, cols;
         cols = frame_width ? width/frame_width : 1;
         rows = frame_height ? height/frame_height : 1;
         retVal = (Frame*) malloc(sizeof(Frame)*(rows*cols+1));
         for(i = 0; i < rows; i++)
         {
                 for(j = 0; j < cols; j++)
                 {
                         retVal[i*rows + j].Position.x = j*frame_width;
                         retVal[i*rows + j].Position.y = i*frame_height;
                 }
         }
         memset(&retVal[rows*cols+1], 0, sizeof(Frame));
         return retVal;
 }
sprite_t* LoadSprite (const char * name, int flags)
Loads a sprite.
Parameters
name The file name of the image to load.
flags The flags.
Returns
null if it fails, else the sprite.
Author
Anthony Rios
Date
3/16/2016
Definition at line 107 of file graphics.c.
References FindFreeSprite(), FindSprite(), gLastSprite, gRenderer, gSprites, and MAX_SPRITES.
Referenced by AddSpritesToEnt(), LoadLevel(), LoadMenu(), and Update().
 {
         SDL_Surface *temp;
         sprite_t *check;
         int position;
         if(!gSprites)
         {
                 return NULL;
         }
         if(abs(gLastSprite) > MAX_SPRITES)
         {
                 gLastSprite = 0;
         }
         if(!name)
         {
                 printf("No name given to load sprite");
                 return NULL;
         }
         if( (check = FindSprite(name, NULL)) != NULL)
         {
                 check->refCount++;
                 return check;
         }
         if( (check = FindFreeSprite(&position)) == NULL)
         {
                 printf("No free sprites");
                 return NULL;
         }
         temp = IMG_Load(name);
         if(!temp)
         {
                 printf("Could not load image : %s \n", name);
                 return NULL;
         }
         check->mSize.x = temp->w;
         check->mSize.y = temp->h;
         check->mTexture = SDL_CreateTextureFromSurface(gRenderer, temp);
         check->name = strdup(name);
         check->refCount = 1;
         check->mFrames = 0;
         SDL_FreeSurface(temp);
         gLastSprite = position;
         return check;
 }
void SDL_SetRect (SDL_Rect * rect, int x, int y, int w, int h)
Sdl set rectangle dimensions.
Parameters
[in,out] rect If non-null, the rectangle to set.
x The x coordinate.
y The y coordinate.
w The width.
h The height.
Author
Anthony Rios
Date
3/29/2016
Definition at line 276 of file graphics.c.
Referenced by DrawSprite(), and ProcessMenuItemsByType().
 {
         rect->x = x;
         rect->y = y;
         rect->w = w;
         rect->h = h;
 }
void ShutdownGraphics ()
Shutdown graphics system, which frees all sprite data.
Author
Anthony Rios
Date
3/30/2016
Definition at line 92 of file graphics.c.
References FreeSprite(), gSprites, and MAX_SPRITES.
Referenced by InitGraphics().
 {
         int i;
         for(i = 0; i < MAX_SPRITES; i++)
         {
                 if(!gSprites[i].refCount)
                 {
                         continue;
                 }
                 FreeSprite(&gSprites[i]);
         }
         free(gSprites);
 }
Variable Documentation
int gLastSprite
Definition at line 15 of file graphics.c.
Referenced by FindFreeSprite(), InitGraphics(), and LoadSprite().
SDL_Renderer* gRedRenderer
Definition at line 13 of file graphics.c.
Referenced by InitGraphics().
SDL_Surface* gRedSurface
Definition at line 11 of file graphics.c.
Referenced by InitGraphics().
SDL_Texture* gRedTexture
Definition at line 12 of file graphics.c.
Referenced by DrawMenuByNum(), DrawMenuByState(), and InitGraphics().
SDL_Renderer* gRenderer
Definition at line 10 of file graphics.c.
Referenced by Draw(), DrawGeneric(), DrawLevel(), DrawMenuByNum(), DrawMenuByState(), DrawSplash(), InitGraphics(), and LoadSprite().
sprite_t* gSprites
Definition at line 14 of file graphics.c.
Referenced by FindFreeSprite(), FindSprite(), FreeSprite(), InitGraphics(), LoadSprite(), and ShutdownGraphics().
SDL_Window* gWindow
Definition at line 9 of file graphics.c.
Referenced by InitGraphics().