Dumb-ways-to-memorize: dumb-ways-to-memorize/mystrings.h File Reference
mystrings.h File Reference
#include <jsmn.h>
Macros
#define ALLOC_STR(X) ((char *) malloc(sizeof(char)*X))
#define GAME_STATE_SPLASH_STR "Splash"
#define GAME_STATE_START_STR "Start"
#define GAME_STATE_GUESS_STR "Guess"
#define GAME_STATE_CHOOSE_STR "Choose"
#define GAME_STATE_PLAYING_STR "Playing"
#define GAME_STATE_END_STR "End"
Functions
char * FileToString (char *file)
char * TypeFromJSON (jsmntype_t Type)
char * JsmnToString (jsmntok_t *token, char *g_str)
char * FindValue (struct object_s *obj, char *key, char *g_str)
void JsmnToInt (jsmntok_t *token, char *str, int *dst)
int StrToInt (char *str)
int CharToInt (char c)
jsmntok_t * FindKey (jsmntok_t *token, char *key, char *g_str)
int ConvertFileToUseable (char *fileName, jsmn_parser *parser, char **stringStorage, jsmntok_t **jsmnStorage)
Macro Definition Documentation
#define ALLOC_STR (X) ((char *) malloc(sizeof(char)*X))
Definition at line 4 of file mystrings.h.
Referenced by FileToString(), and JsmnToString().
#define GAME_STATE_CHOOSE_STR "Choose"
Definition at line 12 of file mystrings.h.
Referenced by StrToGameState().
#define GAME_STATE_END_STR "End"
Definition at line 14 of file mystrings.h.
Referenced by StrToGameState().
#define GAME_STATE_GUESS_STR "Guess"
Definition at line 11 of file mystrings.h.
Referenced by StrToGameState().
#define GAME_STATE_PLAYING_STR "Playing"
Definition at line 13 of file mystrings.h.
Referenced by StrToGameState().
#define GAME_STATE_SPLASH_STR "Splash"
Definition at line 9 of file mystrings.h.
Referenced by StrToGameState().
#define GAME_STATE_START_STR "Start"
Definition at line 10 of file mystrings.h.
Referenced by StrToGameState().
Function Documentation
int CharToInt (char c)
Character to int. A cheap switch statement.
Parameters
c The character.
Returns
An int.
Author
Anthony Rios
Date
2/28/2016
Definition at line 121 of file mystrings.c.
Referenced by StrToInt().
 {
         switch(c)
         {
         case '0': return 0;
         case '1': return 1;
         case '2': return 2;
         case '3': return 3;
         case '4': return 4;
         case '5': return 5;
         case '6': return 6;
         case '7': return 7;
         case '8': return 8;
         case '9': return 9;
         default:
                 return 0;
         }
 }
int ConvertFileToUseable (char * fileName, jsmn_parser * parser, char ** stringStorage, jsmntok_t ** jsmnStorage)
Convert file to useable, by setting the storage for string and jsmntokens, give a filename.
Parameters
[in,out] fileName If non-null, filename of the file.
[in,out] parser If non-null, the parser.
[in,out] stringStorage If non-null, the string storage.
[in,out] jsmnStorage If non-null, the jsmn storage.
Returns
The file converted to useable.
Author
Anthony Rios
Date
3/29/2016
Definition at line 192 of file mystrings.c.
References FileToString(), jsmn_init(), jsmn_parse(), PARSER, STRING, and TOKEN.
Referenced by LoadEntityData(), LoadGameData(), LoadLevel(), LoadMenuData(), LoadPowerUpData(), LoadSelectedLevel(), SetAI_Check(), and UpdatePowerUpMenu().
 {
         int num_tokens, varsToFree = 0;
         jsmn_parser *tempPars;
         char **tempStr;
         jsmntok_t **tempJsmn;
         if(!fileName)
         {
                 printf("Convert File given NULL filename");
                 return -1;
         }
         //Init parser, if not given
         if(!parser)
         {
                 tempPars = (jsmn_parser*) malloc(sizeof(parser));
                 if(!tempPars) return -1;
                 parser = tempPars;
                 varsToFree |= PARSER;
         }
         jsmn_init(parser);
         //Init stringStorage if not given
         if(!stringStorage)
         {
                 tempStr = (char**) malloc(sizeof(char*));
                 if(!tempStr) return -1;
                 stringStorage = tempStr;
                 varsToFree |= STRING;
         }
         *stringStorage = FileToString(fileName);
         if(!*stringStorage)
         {
                 return -1;
         }
         //Init jsmnStorage if not given
         if(!jsmnStorage)
         {
                 tempJsmn = (jsmntok_t**) malloc(sizeof(jsmntok_t*));
                 if(!tempJsmn) return -1;
                 jsmnStorage = tempJsmn;
                 varsToFree |= TOKEN;
         }
         //Actual Parsing
         num_tokens = jsmn_parse(parser, *stringStorage, strlen(*stringStorage), NULL, 0);
         if(num_tokens < 1)
         {
                 printf("Jsmn Parse Eror: %d", num_tokens);
                 return -1;
         }
         *jsmnStorage = (jsmntok_t*) malloc(sizeof(jsmntok_t)*(num_tokens+1));
         if(!*jsmnStorage)
         {
                 return -1;
         }
         jsmn_init(parser); //Reset parser
         num_tokens = jsmn_parse(parser, *stringStorage, strlen(*stringStorage), *jsmnStorage, num_tokens);
         printf("Jsmn returned : %d\n", num_tokens);
         memset( &(*jsmnStorage)[num_tokens], 0, sizeof(jsmntok_t));
         //Freeing if necessary
         if(varsToFree & PARSER) ;
         if(varsToFree & STRING) free(*stringStorage);
         if(varsToFree & TOKEN) free(*jsmnStorage);
         return num_tokens;
 }
char* FileToString (char * file)
Loads string data from a file.
Parameters
[in,out] file If non-null, filename of the file.
Returns
null if it fails, else a char*.
Author
Anthony Rios
Date
1/30/2016
Definition at line 159 of file mystrings.c.
References ALLOC_STR.
Referenced by ConvertFileToUseable().
 {
         char *string;
         int size;
         struct stat st;
         FILE *file;
         stat(fileName, &st);
         file = fopen(fileName, "r");
         if(!file)
         {
                 return NULL;
         }
         size = st.st_size;
         string = ALLOC_STR(size);
         if(!string)
         {
                 printf("Could not allocate memory");
                 exit(-1);
         }
         size = fread(string, sizeof(unsigned char), size, file);
         string[size] = '\0';
         fclose(file);
         return string;
 }
jsmntok_t* FindKey (jsmntok_t * token, char * key, char * g_str)
Searches for the first key that matches given gPlayerName, through through tokens & g_str.
Parameters
[in,out] token The token.
[in,out] key The key.
[in,out] g_str The string to get from.
Returns
null if it fails, else the found key.
Author
Junji
Date
1/30/2016
Definition at line 10 of file mystrings.c.
References CountMem(), JsmnToString(), and jsmntok_t::size.
Referenced by LoadEntityData(), LoadLevel(), LoadLevelData(), ParseAI(), ParsePresetAI(), and ParseToEntity().
 {
         char *str;
         jsmntok_t *local_token = token;
         jsmntok_t* endPtr = token + CountMem(token, sizeof(jsmntok_t));
         if(!local_token || !g_str || !key)
                 return local_token;
         while(local_token < endPtr)
         {
                 if(local_token->size == 1)
                 {
                         str = JsmnToString(local_token, g_str);
                         if(!strcmp(str, key))
{
                                 if(str) free(str);
                                 return local_token;
                         }
                         if(str) free(str);
                 }
                 local_token++;
         }
         return NULL;
 }
char* FindValue (struct object_s * obj, char * key, char * g_str)
Searches for the a value in the object that matches the key string given. Recursive.
Parameters
[in,out] obj If non-null, the object.
[in,out] key If non-null, the key.
[in,out] g_str If non-null, the string.
Returns
null if it fails, else the found value.
Author
Anthony Rios
Date
3/25/2016
Definition at line 53 of file mystrings.c.
References object_t::children, CountMem(), FindValue(), JsmnToString(), object_t::keys, and object_t::values.
Referenced by FindValue(), LoadLevel(), LoadMenu(), LoadMenuData(), ParsePresetAI(), ParseToPowerUp(), and Update().
 {
         int i, keys, objects;
         char *temp_str;
         keys = CountMem(obj->keys, sizeof(jsmntok_t));
         objects = CountMem(obj->children, sizeof(object_t));
         //Iterate through keys
         for(i = 0; i < keys; i++)
         {
                 temp_str = JsmnToString(&obj->keys[i], g_str);
                 if(!temp_str)
                         continue;
                 if(!strcmp(temp_str, key))
                 {
                         if(temp_str) free(temp_str);
                         return JsmnToString(&obj->values[i], g_str);
                 }
                 if(temp_str) free(temp_str);
         }
         //Iterate through children
         for(i = 0; i < objects; i++)
         {
                 if( (temp_str = FindValue(&obj->children[i], key, g_str)) != NULL)
                 {
                         return temp_str;
                 }
                 if(temp_str) free(temp_str);
         }
         return NULL;
 }
void JsmnToInt (jsmntok_t * token, char * str, int * dst)
Jsmn to int.
Parameters
[in,out] token If non-null, the token.
[in,out] str If non-null, the string.
[in,out] dst If non-null, destination for the value.
Author
Anthony Rios
Date
2/28/2016
Definition at line 84 of file mystrings.c.
References JsmnToString(), and StrToInt().
Referenced by LoadLevelData(), and ParseToEntity().
 {
         char *temp;
         temp = JsmnToString(token, str);
         *dst = StrToInt(temp);
         if(temp) free(temp);
 }
char* JsmnToString (jsmntok_t * token, char * g_str)
Jsmn to string.
Parameters
[in,out] token If non-null, the token.
[in,out] g_str If non-null, the global string.
Returns
null if it fails, else a char*.
Author
Anthony Rios
Date
1/30/2016
Definition at line 34 of file mystrings.c.
References ALLOC_STR, jsmntok_t::end, and jsmntok_t::start.
Referenced by FindKey(), FindValue(), JsmnToInt(), LoadGameData(), LoadLevel(), LoadLevelData(), LoadMenuData(), LoadPowerUpData(), MiniParseFunc(), ParseAI(), ParsePresetAI(), ParseToEntity(), ParseToObject(), ParseToStringArray(), ParseToVec2(), PrintObject(), SetAI_Action(), and UpdatePowerUpMenu().
 {
         int size = token->end - token->start;
         char *retVal;
         if(size < 0)
         {
                 return NULL;
         }
         retVal = ALLOC_STR(size+1);
         if(!retVal)
         {
                 printf("Could not allocate memory");
                 exit(-1);
         }
         strncpy( retVal, &g_str[token->start], size);
         retVal[size] = 0;
         return retVal;
 }
int StrToInt (char * str)
String to int.
Parameters
[in,out] str If non-null, the string.
Returns
An int.
Author
Anthony Rios
Date
2/28/2016
Definition at line 92 of file mystrings.c.
References CharToInt().
Referenced by JsmnToInt(), LoadLevel(), MiniParseFunc(), ParseAI(), ParseToVec2(), SetAI_Check(), and SetAI_Var().
 {
         int i, retVal, length, neg;
         if(str == NULL)
         {
                 return 0;
         }
         length = strlen(str);
         retVal = 0;
         neg = 0;
         if(str[0] == '-')
         {
                 i = 1;
                 neg = 1;
         } else
         {
                 i = 0;
         }
         for(i; i < length; i++)
         {
                 retVal += CharToInt(str[i])*(powf( 10, (length-i-1) ) );
         }
         if(neg)
         {
                 retVal *= -1;
         }
         return retVal;
 }
char* TypeFromJSON (jsmntype_t Type)
Type string from JSON string.
Parameters
Type The type.
Returns
null if it fails, else a char*.
Author
Anthony Rios
Date
1/30/2016
Definition at line 140 of file mystrings.c.
References JSMN_ARRAY, JSMN_OBJECT, JSMN_PRIMITIVE, JSMN_STRING, and JSMN_UNDEFINED.
 {
         switch(Type)
         {
         case(JSMN_UNDEFINED):
                 return "UNDEFINED";
         case(JSMN_OBJECT):
                 return "OBJECT";
         case(JSMN_ARRAY):
                 return "ARRAY";
         case(JSMN_STRING):
                 return "STRING";
         case(JSMN_PRIMITIVE):
                 return "PRIMITIVE";
         default:
                 return "UNKOWN";
         }
 }