Dumb-ways-to-memorize: dumb-ways-to-memorize/parsevariable.h File Reference
parsevariable.h File Reference
#include "entity.h"
#include "parseobject.h"
Enumerations
enum EntityMembers {
ENTITY_MEMBER_HAZARDS,
ENTITY_MEMBER_HEALTH,
ENTITY_MEMBER_COLLISION_TYPE,
ENTITY_MEMBER_ENTITY_STATE,
ENTITY_MEMBER_SPRITES,
ENTITY_MEMBER_ACCEL,
ENTITY_MEMBER_VELOCITY,
ENTITY_MEMBER_POSITION,
ENTITY_MEMBER_MAX
}
enum OtherNumbers {
HEIGHT,
WIDTH,
FRAMES
}
Functions
void EditEntity (entity_t *ent, EntityMembers member, void *value)
void MiniParseFunc (entity_t *ent, jsmntok_t *token, char *str, EntityMembers member, int size)
entity_t * ParseToEntity (object_t *object, char *str)
vec2_t * ParseToVec2 (object_t *object, char *str)
char ** ParseToStringArray (object_t *object, char *str)
Variables
char * AssignableVariableNames []
char * OtherVariableNames []
Enumeration Type Documentation
enum EntityMembers
Defines the enum for variables in the entity structure
Enumerator
ENTITY_MEMBER_HAZARDS
An enum constant representing the entity member hazards
ENTITY_MEMBER_HEALTH
An enum constant representing the entity member health
ENTITY_MEMBER_COLLISION_TYPE
An enum constant representing the entity member collision type
ENTITY_MEMBER_ENTITY_STATE
An enum constant representing the entity member entity state
ENTITY_MEMBER_SPRITES
An enum constant representing the entity member sprites
ENTITY_MEMBER_ACCEL
An enum constant representing the entity member accel
ENTITY_MEMBER_VELOCITY
An enum constant representing the entity member velocity
ENTITY_MEMBER_POSITION
An enum constant representing the entity member position
ENTITY_MEMBER_MAX
Definition at line 11 of file parsevariable.h.
 {
         ENTITY_MEMBER_HAZARDS,  /**< An enum constant representing the entity member hazards */
         ENTITY_MEMBER_HEALTH,   /**< An enum constant representing the entity member health */
         ENTITY_MEMBER_COLLISION_TYPE,   /**< An enum constant representing the entity member collision type */
         ENTITY_MEMBER_ENTITY_STATE, /**< An enum constant representing the entity member entity state */
         ENTITY_MEMBER_SPRITES,  /**< An enum constant representing the entity member sprites  */
         ENTITY_MEMBER_ACCEL,    /**< An enum constant representing the entity member accel  */
         ENTITY_MEMBER_VELOCITY, /**< An enum constant representing the entity member velocity  */
         ENTITY_MEMBER_POSITION, /**< An enum constant representing the entity member position */
         ENTITY_MEMBER_MAX
 }EntityMembers;
enum OtherNumbers
Defines the enum for graphics members in the entity
Enumerator
HEIGHT
An enum constant representing the heights of the sprites
WIDTH
An enum constant representing the widths of th sprites
FRAMES
An enum constant representing the number of frames in each sprite
Definition at line 26 of file parsevariable.h.
 {
         HEIGHT, /**< An enum constant representing the heights of the sprites */
         WIDTH,  /**< An enum constant representing the widths of th sprites */
         FRAMES  /**< An enum constant representing the number of frames in each sprite */
 }OtherNumbers;
Function Documentation
void EditEntity (entity_t * ent, EntityMembers member, void * value)
Directly Edit the entity with the given data and member type.
Parameters
[in,out] ent If non-null, the ent.
member The member.
[in,out] value If non-null, the value.
Author
Anthony Rios
Date
3/30/2016
Definition at line 15 of file parsevariable.c.
References ENTITY_MEMBER_ACCEL, ENTITY_MEMBER_COLLISION_TYPE, ENTITY_MEMBER_ENTITY_STATE, ENTITY_MEMBER_HAZARDS, ENTITY_MEMBER_HEALTH, ENTITY_MEMBER_POSITION, ENTITY_MEMBER_SPRITES, and ENTITY_MEMBER_VELOCITY.
Referenced by MiniParseFunc(), and ParseToEntity().
 {
         if(value == NULL)
         {
                 return;
         }
         switch(member)
         {
         case ENTITY_MEMBER_HAZARDS: ent->mHazards = (int) value; break;
         case ENTITY_MEMBER_HEALTH: ent->mHealth = (int) value; break;
         case ENTITY_MEMBER_COLLISION_TYPE: ent->mCollisionType = (collision_type_t) (int) value; break;
         case ENTITY_MEMBER_ENTITY_STATE: ent->mEntityState = (entity_state_t) (int) value; break;
         case ENTITY_MEMBER_SPRITES: ent->mSprites = (sprite_t**) value; break;
         case ENTITY_MEMBER_ACCEL: ent->mAccel = *((vec2_t*) value); break;
         case ENTITY_MEMBER_VELOCITY : ent->mVelocity = *((vec2_t*) value); break;
         case ENTITY_MEMBER_POSITION : ent->mPosition = *((vec2_t*) value); break;
         default:
                 break;
         }
 }
void MiniParseFunc (entity_t * ent, jsmntok_t * token, char * str, EntityMembers member, int size)
Mini parse function, handles entering / converting the data into the entity given.
Parameters
[in,out] ent If non-null, the ent.
[in,out] token If non-null, the token.
[in,out] str If non-null, the string.
member The member.
size The size.
Author
Anthony Rios
Date
3/29/2016
Definition at line 136 of file parsevariable.c.
References EditEntity(), ENTITY_MEMBER_COLLISION_TYPE, ENTITY_MEMBER_ENTITY_STATE, ENTITY_MEMBER_HAZARDS, ENTITY_MEMBER_SPRITES, JsmnToString(), LoadSprite(), StrToCollisionType(), StrToEntityState(), StrToHazard(), and StrToInt().
Referenced by ParseToEntity().
 {
         int i;
         char *temp = NULL;
         int checkInt = 0;
         sprite_t **checkSprite = NULL;
         if(!ent || !token || !str)
                 return;
         if(member== ENTITY_MEMBER_HAZARDS)
         {
                 for(i= 0; i < size; i++)
                 {
                         temp = JsmnToString(&token[i], str);
                         checkInt += StrToHazard(temp);
                         if(temp) free(temp);
                 }
                 EditEntity(ent, member, (void*)checkInt);
         } else if(member== ENTITY_MEMBER_SPRITES)
         {
                 checkSprite = (sprite_t**) malloc(sizeof(sprite_t*)*(size+1));
                 if(!checkSprite)
                 {
                         return;
                 }
                 for(i = 0; i < size; i++)
                 {
                         temp = JsmnToString(&token[i], str);
                         checkSprite[i] = LoadSprite(temp, 0);
                         if(temp) free(temp);
                 }
                 memset(&checkSprite[size], 0, sizeof(sprite_t*));
                 EditEntity(ent, member, checkSprite);
         } else if(member == ENTITY_MEMBER_COLLISION_TYPE)
         {
                 temp = JsmnToString(token, str);
                 EditEntity(ent, member, (void*)StrToCollisionType(temp));
                 if(temp) free(temp);
         } else if (member == ENTITY_MEMBER_ENTITY_STATE)
         {
                 temp = JsmnToString(token, str);
                 EditEntity(ent, member, (void*)StrToEntityState(temp));
                 if(temp) free(temp);
         }else
         {
                 temp = JsmnToString(token, str);
                 EditEntity(ent, member, (void*)StrToInt(temp));
                 if(temp) free(temp);
         }
 }
entity_t* ParseToEntity (object_t * object, char * str)
Parse to entity. Tries to Assign everything , but the entity function pointers. Current Frame = 0, Weight = 1
Parameters
[in,out] object If non-null, the object.
[in,out] str If non-null, the string.
Returns
null if it fails, else a pointer to an entity_t.
Author
Anthony Rios
Date
3/21/2016
Definition at line 36 of file parsevariable.c.
References AssignableVariableNames, CountMem(), DrawGeneric(), EditEntity(), ENTITY_MEMBER_HAZARDS, ENTITY_MEMBER_SPRITES, FindKey(), FindObject(), FRAMES, HEIGHT, JSMN_STRING, JsmnToInt(), JsmnToString(), LoadAnimation(), MAX_ANIMATIONS, MiniParseFunc(), OtherVariableNames, ParseToVec2(), PrintEntity(), ThinkGeneric(), TouchGeneric(), jsmntok_t::type, and WIDTH.
Referenced by LoadEntityData().
 {
         int i, j, checkInt, heights[MAX_ANIMATIONS] = {0}, widths[MAX_ANIMATIONS] = {0}, frames[MAX_ANIMATIONS] = {0};
         char *temp;
         entity_t *retVal;
         Frame *checkFrame = NULL;
         jsmntok_t *checkTok = NULL;
         object_t *checkObj = NULL;
         if(!object || !str)
                 return NULL;
         retVal = (entity_t*) malloc(sizeof(entity_t));
         memset(retVal, 0, sizeof(entity_t));
         retVal->mName = object->name;
         for(i = 0; AssignableVariableNames[i]; i++)
         {
                 if( (checkTok = FindKey(object->keys, AssignableVariableNames[i], str)) != NULL)
                 {
                         if(checkTok->type == JSMN_STRING)
{
                                 if(i == ENTITY_MEMBER_HAZARDS || i == ENTITY_MEMBER_SPRITES)
{
                                         checkInt = abs((int) object->keys - (int) checkTok)/sizeof(jsmntok_t);
                                         MiniParseFunc(retVal, &object->values[checkInt], str, (EntityMembers)i, 1);
                                         checkTok = NULL;
                                 } else
{
                                         checkInt = abs((int) object->keys - (int) checkTok)/sizeof(jsmntok_t);
                                         MiniParseFunc(retVal, &object->values[checkInt], str, (EntityMembers)i, 1);
                                         checkTok = NULL;
                                 }
                         }else
{
                                 temp = JsmnToString(checkTok, str);
                                 printf("Error Unkown var %s", temp);
                                 free(temp);
                         }
                 } else if( (checkObj = FindObject(object, AssignableVariableNames[i])) != NULL)
                 {
                         if(i == ENTITY_MEMBER_HAZARDS || i == ENTITY_MEMBER_SPRITES)
{
                                 MiniParseFunc(retVal, checkObj->values, str, (EntityMembers)i, CountMem(checkObj->values, sizeof(jsmntok_t)));
                         } else if(CountMem(&checkObj->values, sizeof(jsmntok_t)) == 2)
{
                                 EditEntity(retVal, (EntityMembers)i, ParseToVec2(checkObj, str));
                         } else
{
                                 printf("Error with : %s in JSON file \n", object->name);
                         }
                 }
         }
         for(i = 0; OtherVariableNames[i]; i++)
         {
                 if( (checkObj = FindObject(object, OtherVariableNames[i])) != NULL)
                 {
                         for(j = 0; checkObj->values[j].type; j++)
{
                                 switch(i)
{
                                 case HEIGHT: JsmnToInt(&checkObj->values[j], str, &heights[j]); break;
                                 case WIDTH: JsmnToInt(&checkObj->values[j], str, &widths[j]); break;
                                 case FRAMES: JsmnToInt(&checkObj->values[j], str, &frames[j]); break;
                                 default:
                                         break;
                                 }
                         }
                 } else if ( (checkTok = FindKey(object->keys, OtherVariableNames[i], str)) != NULL)
                 {
                         switch(i)
{
                                 case HEIGHT: JsmnToInt(checkTok, str, &heights[0]); break;
                                 case WIDTH: JsmnToInt(checkTok, str, &widths[0]); break;
                                 case FRAMES: JsmnToInt(checkTok, str, &frames[0]); break;
                                 default:
                                         break;
                                 }
                 }
         }
         //retVal->mSprites = (sprite_t**) malloc(sizeof(sprite_t*)*(j+1));
         //retVal->mSprites[j] = NULL;
         if(retVal->mSprites)
         {
                 for(i = 0; retVal->mSprites[i]; i++)
                 {
                         if(!retVal->mSprites[i])
                                 break;
                         checkFrame = LoadAnimation(widths[i], heights[i], retVal->mSprites[i]->mSize.x, retVal->mSprites[i]->mSize.y);
                         retVal->mSprites[i]->mFrames = frames[i] ? frames[i] : 1;
                         memcpy(&retVal->mSprites[i]->mAnimations, checkFrame, sizeof(Frame)*retVal->mSprites[i]->mFrames );
                 }
         }
         retVal->mNextThink = 1;
         retVal->mCurrentFrame = 0;
         retVal->mWeight = 1;
         retVal->Think = ThinkGeneric;
         retVal->Draw = DrawGeneric;
         retVal->Touch = TouchGeneric;
         PrintEntity(retVal);
         return retVal;
 }
char** ParseToStringArray (object_t * object, char * str)
Parse obj/data to string array.
Parameters
[in,out] object If non-null, the object.
[in,out] str If non-null, the string.
Returns
null if it fails, else a handle to a char.
Author
Anthony Rios
Date
3/29/2016
Definition at line 203 of file parsevariable.c.
References CountMem(), and JsmnToString().
Referenced by LoadEntityData(), and LoadLevel().
 {
         int i, size;
         char *temp;
         char **retVal;
         if(!object || !str)
                 return NULL;
         size = CountMem(object->values, sizeof(jsmntok_t));
         retVal = (char**) malloc(sizeof(char*)*(size+1));
         for(i = 0; i < size; i++)
         {
                 temp = JsmnToString(&object->values[i], str);
                 retVal[i] = temp;
         }
         retVal[size+1] = 0;
         return retVal;
 }
vec2_t* ParseToVec2 (object_t * object, char * str)
Parse given obj/str to vector 2.
Parameters
[in,out] object If non-null, the object.
[in,out] str If non-null, the string.
Returns
null if it fails, else a pointer to a vec2_t.
Author
Anthony Rios
Date
3/29/2016
Definition at line 186 of file parsevariable.c.
References JsmnToString(), StrToInt(), vec2_t::x, and vec2_t::y.
Referenced by LoadGameData(), LoadLevel(), ParseToEntity(), and SetAI_Action().
 {
         vec2_t *retVal;
         char *temp1, *temp2;
         retVal = (vec2_t*) malloc(sizeof(vec2_t));
         if(!retVal || !object || !str)
         {
                 return NULL;
         }
         temp1 = JsmnToString(&object->values[0], str);
         temp2 = JsmnToString(&object->values[1], str);
         retVal->x = StrToInt(temp1);
         retVal->y = StrToInt(temp2);
         free(temp1); free(temp2);
         return retVal;
 }
Variable Documentation
char* AssignableVariableNames[]
Definition at line 11 of file parsevariable.c.
Referenced by ParseToEntity().
char* OtherVariableNames[]
Definition at line 12 of file parsevariable.c.
Referenced by ParseToEntity().