Dumb-ways-to-memorize: dumb-ways-to-memorize/parseentity.h File Reference
parseentity.h File Reference
#include "entity.h"
#include "parseobject.h"
Enumerations
enum entity_members_complex_t {
ENTITY_MEMBER_HAZARDS,
ENTITY_MEMBER_COLLISION_TYPE,
ENTITY_MEMBER_ENTITY_STATE,
ENTITY_MEMBER_MAX
}
enum entity_members_vector2_t {
ENTITY_MEMBER_ACCEL,
ENTITY_MEMBER_VELOCITY,
ENTITY_MEMBER_POSITION
}
enum entity_members_simple_t {
ENTITY_MEMBER_SPRITE,
ENTITY_MEMBER_HEALTH,
ENTITY_MEMBER_DAMAGE,
ENTITY_MEMBER_HEIGHT,
ENTITY_MEMBER_WIDTH,
ENTITY_MEMBER_FRAMES
}
Functions
void AddComplexMemToEnt (entity_t *ent, entity_members_complex_t member, void *value)
void ParseComplexMember (entity_t *ent, jsmntok_t *token, char *str, entity_members_complex_t member, int size)
void AddVector2Entity (entity_t *ent, entity_members_vector2_t member, vec2_t *value)
void AddSpritesToEnt (entity_t *ent, char **files, int size)
entity_t * ParseToEntity (object_t *object, char *str)
Variables
char * ComplexVariableNames []
char * Vector2VariableNames []
char * SimpleVariableNames []
Enumeration Type Documentation
enum entity_members_complex_t
Defines the enum for variables in the entity structure
Enumerator
ENTITY_MEMBER_HAZARDS
An enum constant representing the entity member hazards
ENTITY_MEMBER_COLLISION_TYPE
An enum constant representing the entity member collision type
ENTITY_MEMBER_ENTITY_STATE
An enum constant representing the entity member entity state
ENTITY_MEMBER_MAX
Definition at line 12 of file parseentity.h.
 {
         ENTITY_MEMBER_HAZARDS,  /**< An enum constant representing the entity member hazards */
         ENTITY_MEMBER_COLLISION_TYPE,   /**< An enum constant representing the entity member collision type */
         ENTITY_MEMBER_ENTITY_STATE, /**< An enum constant representing the entity member entity state */
         ENTITY_MEMBER_MAX
 }entity_members_complex_t;
enum entity_members_simple_t
Defines the enum for simple members in the entity
Enumerator
ENTITY_MEMBER_SPRITE
An enum constant representing the sprite file names
ENTITY_MEMBER_HEALTH
An enum constant representing the default health of the entity
ENTITY_MEMBER_DAMAGE
An enum constant representing the damage the entity deals on collision
ENTITY_MEMBER_HEIGHT
An enum constant representing the heights of the sprites
ENTITY_MEMBER_WIDTH
An enum constant representing the widths of th sprites
ENTITY_MEMBER_FRAMES
An enum constant representing the number of frames in each sprite
Definition at line 30 of file parseentity.h.
 {
         ENTITY_MEMBER_SPRITE, /**< An enum constant representing the sprite file names */
         ENTITY_MEMBER_HEALTH, /**< An enum constant representing the default health of the entity */
         ENTITY_MEMBER_DAMAGE, /**< An enum constant representing the damage the entity deals on collision */
         ENTITY_MEMBER_HEIGHT, /**< An enum constant representing the heights of the sprites */
         ENTITY_MEMBER_WIDTH,  /**< An enum constant representing the widths of th sprites */
         ENTITY_MEMBER_FRAMES  /**< An enum constant representing the number of frames in each sprite */
 }entity_members_simple_t;
enum entity_members_vector2_t
Defines the enum for variables in the entity struct with vec2_t values
Enumerator
ENTITY_MEMBER_ACCEL
An enum constant representing the entity member accel
ENTITY_MEMBER_VELOCITY
An enum constant representing the entity member velocity
ENTITY_MEMBER_POSITION
An enum constant representing the entity member position
Definition at line 21 of file parseentity.h.
 {
         ENTITY_MEMBER_ACCEL,    /**< An enum constant representing the entity member accel  */
         ENTITY_MEMBER_VELOCITY, /**< An enum constant representing the entity member velocity  */
         ENTITY_MEMBER_POSITION, /**< An enum constant representing the entity member position */
 }entity_members_vector2_t;
Function Documentation
void AddComplexMemToEnt (entity_t * ent, entity_members_complex_t member, void * value)
Alias for a switch case that handles complex member to entity.
Parameters
[in,out] ent If non-null, the ent.
member The member.
[in,out] value If non-null, the value.
Author
Anthony Rios
Date
3/30/2016
Definition at line 15 of file parseentity.c.
References ENTITY_MEMBER_COLLISION_TYPE, ENTITY_MEMBER_ENTITY_STATE, and ENTITY_MEMBER_HAZARDS.
Referenced by ParseComplexMember().
 {
         if(!value || !ent)
         {
                 return;
         }
         switch(member)
         {
         case ENTITY_MEMBER_HAZARDS: ent->mHazards = (int) value; break;
         case ENTITY_MEMBER_COLLISION_TYPE: ent->mCollisionType = (collision_type_t) (int) value; break;
         case ENTITY_MEMBER_ENTITY_STATE: ent->mEntityState = (entity_state_t) (int) value; break;
         default:
                 break;
         }
 }
void AddSpritesToEnt (entity_t * ent, char ** files, int size)
Loads and adds the sprite files given to the entity.
Parameters
[in,out] ent If non-null, the ent.
[in,out] files If non-null, an array of the strings with file names of the sprites.
size The size.
Author
Anthony Rios
Date
3/31/2016
Definition at line 49 of file parseentity.c.
References LoadSprite().
Referenced by ParseToEntity().
 {
         int i;
         sprite_t **checkSprite;
         if(!files || !ent)
         {
                 return;
         }
         checkSprite = (sprite_t**) malloc(sizeof(sprite_t*)*(size+1));
         if(!checkSprite)
         {
                 return;
         }
         for(i = 0; i < size; i++)
         {
                 checkSprite[i] = LoadSprite(files[i], 0);
         }
         checkSprite[size] = NULL;
         ent->mSprites = checkSprite;
 }
void AddVector2Entity (entity_t * ent, entity_members_vector2_t member, vec2_t * value)
Adds a vector2 to the entity, which is a switch case similar to AddComplexMemToEnt.
Parameters
[in,out] ent If non-null, the ent.
member The vector member to enters.
[in,out] value If non-null, the value of the vector.
Author
Anthony Rios
Date
3/31/2016
Definition at line 32 of file parseentity.c.
References ENTITY_MEMBER_ACCEL, ENTITY_MEMBER_POSITION, and ENTITY_MEMBER_VELOCITY.
Referenced by ParseToEntity().
 {
         if(!value || !ent)
         {
                 return;
         }
         switch(member)
         {
         case ENTITY_MEMBER_ACCEL: ent->mAccel = *value; break;
         case ENTITY_MEMBER_POSITION: ent->mPosition = *value; break;
         case ENTITY_MEMBER_VELOCITY: ent->mVelocity = *value; break;
         default:
                 break;
         }
 }
void ParseComplexMember (entity_t * ent, jsmntok_t * token, char * str, entity_members_complex_t member, int size)
Handles entering / converting complex members into the entity given.
Parameters
[in,out] ent If non-null, the ent.
[in,out] token If non-null, the token(s) to parse.
[in,out] str If non-null, the global string to parse tokens from.
member The complex member associated with values given.
size The amount of values to input.
Author
Anthony Rios
Date
3/29/2016
Definition at line 166 of file parseentity.c.
References AddComplexMemToEnt(), ENTITY_MEMBER_COLLISION_TYPE, ENTITY_MEMBER_ENTITY_STATE, ENTITY_MEMBER_HAZARDS, JsmnToString(), StrToCollisionType(), StrToEntityState(), and StrToHazard().
Referenced by ParseToEntity().
 {
         int i;
         char *temp;
         int checkInt = 0;
         if(!ent || !token || !str)
                 return;
         if(member== ENTITY_MEMBER_HAZARDS)
         {
                 for(i= 0; i < size; i++)
                 {
                         temp = JsmnToString(&token[i], str);
                         checkInt += StrToHazard(temp);
                         if(temp) free(temp);
                 }
                 AddComplexMemToEnt(ent, member, (void*)checkInt);
         }else if(member == ENTITY_MEMBER_COLLISION_TYPE)
         {
                 temp = JsmnToString(token, str);
                 AddComplexMemToEnt(ent, member, (void*)StrToCollisionType(temp));
                 if(temp) free(temp);
         } else if (member == ENTITY_MEMBER_ENTITY_STATE)
         {
                 temp = JsmnToString(token, str);
                 AddComplexMemToEnt(ent, member, (void*)StrToEntityState(temp));
                 if(temp) free(temp);
         }
 }
entity_t* ParseToEntity (object_t * object, char * str)
Parse to entity. Tries to Assign everything , and defaults all function pointers to generic. Current Frame = 0, Weight = 1
Parameters
[in,out] object If non-null, the object.
[in,out] str If non-null, the string.
Returns
null if it fails, else a pointer to an entity_t.
Author
Anthony Rios
Date
3/21/2016
Definition at line 70 of file parseentity.c.
References AddSpritesToEnt(), AddVector2Entity(), ComplexVariableNames, CountMem(), DrawGeneric(), ENTITY_MEMBER_DAMAGE, ENTITY_MEMBER_FRAMES, ENTITY_MEMBER_HEALTH, ENTITY_MEMBER_HEIGHT, ENTITY_MEMBER_SPRITE, ENTITY_MEMBER_WIDTH, FindKey(), FindObject(), JsmnToInt(), JsmnToString(), LoadAnimation(), MAX_ANIMATIONS, ParseComplexMember(), ParseToVec2(), PrintEntity(), SimpleVariableNames, ThinkGeneric(), TouchGeneric(), and Vector2VariableNames.
Referenced by LoadEntityData().
 {
         int i, j, position, size, heights[MAX_ANIMATIONS] = {0}, widths[MAX_ANIMATIONS] = {0}, frames[MAX_ANIMATIONS] = {0};
         char **spriteFiles;
         entity_t *retVal;
         Frame *checkFrame = NULL;
         jsmntok_t *checkTok = NULL;
         object_t *checkObj = NULL;
         if(!object || !str)
                 return NULL;
         retVal = (entity_t*) malloc(sizeof(entity_t));
         spriteFiles = (char**) malloc(sizeof(char*)*(MAX_ANIMATIONS+1));
         memset(spriteFiles, 0, sizeof(char*)*(MAX_ANIMATIONS+1));
         memset(retVal, 0, sizeof(entity_t));
         retVal->mName = object->name;
         for(i = 0; ComplexVariableNames[i]; i++)
         {
                 if( (checkTok = FindKey(object->keys, ComplexVariableNames[i], str)) != NULL)
                 {
                         position = checkTok - object->keys;
                         ParseComplexMember(retVal, &object->values[position], str, (entity_members_complex_t)i, 1);
                         checkTok = NULL;
                 }
                 else if( (checkObj = FindObject(object, ComplexVariableNames[i])) != NULL)
                 {
                         size = CountMem(checkObj->values, sizeof(jsmntok_t));
                         ParseComplexMember(retVal, checkObj->values, str, (entity_members_complex_t)i, size);
                         checkObj = NULL;
                 }
         }
         for(i = 0; Vector2VariableNames[i]; i++)
         {
                 if( (checkObj = FindObject(object, Vector2VariableNames[i])) != NULL)
                 {
                         AddVector2Entity(retVal, (entity_members_vector2_t) i, ParseToVec2(checkObj, str));
                 }
         }
         for(i = 0; SimpleVariableNames[i]; i++)
         {
                 if( (checkObj = FindObject(object, SimpleVariableNames[i])) != NULL)
                 {
                         for(j = 0; checkObj->values[j].type; j++)
{
                                 switch(i)
{
                                 case ENTITY_MEMBER_SPRITE: spriteFiles[j] = JsmnToString(&checkObj->values[j], str); break;
                                 case ENTITY_MEMBER_HEIGHT: JsmnToInt(&checkObj->values[j], str, &heights[j]); break;
                                 case ENTITY_MEMBER_WIDTH: JsmnToInt(&checkObj->values[j], str, &widths[j]); break;
                                 case ENTITY_MEMBER_FRAMES: JsmnToInt(&checkObj->values[j], str, &frames[j]); break;
                                 default:
                                         break;
                                 }
                         }
                 } else if ( (checkTok = FindKey(object->keys, SimpleVariableNames[i], str)) != NULL)
                 {
                         switch(i)
{
                                 case ENTITY_MEMBER_SPRITE: spriteFiles[0] = JsmnToString(&checkObj->values[0], str); break;
                                 case ENTITY_MEMBER_HEALTH: JsmnToInt(checkTok, str, &retVal->mHealth); break;
                                 case ENTITY_MEMBER_DAMAGE: JsmnToInt(checkTok, str, &retVal->mDamage); break;
                                 case ENTITY_MEMBER_HEIGHT: JsmnToInt(checkTok, str, &heights[0]); break;
                                 case ENTITY_MEMBER_WIDTH: JsmnToInt(checkTok, str, &widths[0]); break;
                                 case ENTITY_MEMBER_FRAMES: JsmnToInt(checkTok, str, &frames[0]); break;
                                 default:
                                         break;
                                 }
                 }
         }
         AddSpritesToEnt(retVal, spriteFiles, CountMem(spriteFiles, sizeof(char*)));
         if(retVal->mSprites)
         {
                 for(i = 0; retVal->mSprites[i]; i++)
                 {
                         if(!retVal->mSprites[i])
                                 break;
                         checkFrame = LoadAnimation(widths[i], heights[i], retVal->mSprites[i]->mSize.x, retVal->mSprites[i]->mSize.y);
                         retVal->mSprites[i]->mFrames = frames[i] ? frames[i] : 1;
                         memcpy(&retVal->mSprites[i]->mAnimations, checkFrame, sizeof(Frame)*retVal->mSprites[i]->mFrames );
                 }
         }
         retVal->mNextThink = 1;
         retVal->mCurrentFrame = 0;
         retVal->mWeight = 1;
         retVal->Think = ThinkGeneric;
         retVal->Draw = DrawGeneric;
         retVal->Touch = TouchGeneric;
         PrintEntity(retVal);
         return retVal;
 }
Variable Documentation
char* ComplexVariableNames[]
The complex variables which need more processing to parse
Definition at line 11 of file parseentity.c.
Referenced by ParseToEntity().
char* SimpleVariableNames[]
The simple variables are there given values
Definition at line 13 of file parseentity.c.
Referenced by ParseToEntity().
char* Vector2VariableNames[]
The variables which parse to vectors
Definition at line 12 of file parseentity.c.
Referenced by ParseToEntity().