Dumb-ways-to-memorize: dumb-ways-to-memorize/game.c File Reference
game.c File Reference
#include "globals.h"
#include "quick_controller.h"
#include "game.h"
#include "entity.h"
#include "mystrings.h"
#include "parseobject.h"
#include "parsevariable.h"
#include "parsepowerup.h"
#include "parselevel.h"
#include "dumb_physics.h"
#include "player.h"
#include "graphics.h"
#include <SDL.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "menu.h"
Functions
int LoadGameData ()
int LoadEntityData ()
int LoadLevelData ()
int LoadPowerUpData ()
int LoadMenuData ()
int SelectLevels ()
void RandomizeSelectedLevels ()
int LoadSelectedLevel (int level)
void Poll ()
void UpdatePlaying ()
void Update ()
void DrawSplash ()
void DrawStart ()
void DrawGuess ()
void DrawChoose ()
void DrawPlaying ()
void Draw ()
int Setup ()
int Run ()
void Shutdown ()
Variables
int exitRequest = 0
int gDelay = 0
int gLevelsPerGame = LEVELS_DEFAULT
jsmn_parser gParser
char ** gLevels = NULL
char ** gSelectedLevels = NULL
char ** gSelectedPowerUps = NULL
char ** gUsedPowerUps = NULL
jsmntok_t * gGameTokens
jsmntok_t * gEntityTokens
jsmntok_t * gLevelTokens
object_t * gGameObject
object_t * gEntityObject
object_t * gLevelObject
char * gGameData
char * gEntityData
char * gLevelData
char * gEntitiesFile = NULL
char * gPowerUpsFile = NULL
entity_t * gEntityDictionary
power_t * gPowerUps
char * gCurrentPowerUpName = NULL
GameState gGameState = SPLASH
sprite_t * gSplash = NULL
vec2_t gZeroPos = {0,0}
SDL_Event gEventQ
SDL_GameController * gController = NULL
SDL_GameControllerButton gButtonQ
unsigned int gCurrentTime = 0
Function Documentation
void Draw ()
Definition at line 547 of file game.c.
References CHOOSE, DrawChoose(), DrawGuess(), DrawPlaying(), DrawSplash(), DrawStart(), gGameState, gRenderer, GUESS, PLAYING, SPLASH, and START.
Referenced by DrawEntities(), and Run().
 {
         SDL_RenderClear(gRenderer);
         switch(gGameState)
         {
         case(SPLASH):
                 {
                         DrawSplash();
                         break;
                 }
         case(START):
                 {
                         DrawStart();
                         break;
                 }
         case(CHOOSE):
                 {
                         DrawChoose();
                         break;
                 }
         case(GUESS):
                 {
                         DrawGuess();
                         break;
                 }
         case(PLAYING):
                 {
                         DrawPlaying();
                         break;
                 }
         default:
                 break;
         }
         SDL_RenderPresent(gRenderer);
         return;
 }
void DrawChoose ()
Draws the screen for the player to choose which powerUp he wants for this level.
Author
Anthony Rios
Date
3/29/2016
Definition at line 745 of file game.c.
References exitRequest, and gMenus.
Referenced by Draw(), and Update().
 {
         if(!gMenus)
         {
                 printf("No menus loaded");
                 exitRequest = 1;
                 return;
         }
         gMenus[2].Draw(&gMenus[2]);
 }
void DrawGuess ()
Draws the screen to player for powers to choose for this run.
Author
Anthony Rios
Date
3/29/2016
Definition at line 727 of file game.c.
References exitRequest, and gMenus.
Referenced by Draw(), and Update().
 {
         if(!gMenus)
         {
                 printf("No menus loaded");
                 exitRequest = 1;
                 return;
         }
         gMenus[1].Draw(&gMenus[1]);
         return;
 }
void DrawPlaying ()
Draws the main game state, which is playing the game.
Author
Anthony Rios
Date
3/29/2016
Definition at line 763 of file game.c.
References DrawEntities(), and DrawLevel().
Referenced by Draw(), and Update().
 {
         DrawLevel();
         DrawEntities();
         return;
 }
void DrawSplash ()
Draws the splash screen.
Author
Anthony Rios
Date
3/29/2016
Definition at line 691 of file game.c.
References DrawSprite(), gRenderer, and gSplash.
Referenced by Draw(), and Update().
 {
         if(gSplash)
         {
                 if(DrawSprite(gSplash, NULL, &gZeroPos, gRenderer))
                 {
                         printf("Couldn't draw splash: %s \n", SDL_GetError());
                 }
         }
         return;
 }
void DrawStart ()
Draws the start screen.
Author
Anthony Rios
Date
3/29/2016
Definition at line 709 of file game.c.
References exitRequest, and gMenus.
Referenced by Draw(), and Update().
 {
         if(!gMenus)
         {
                 printf("No menus loaded");
                 exitRequest = 1;
                 return;
         }
         gMenus[0].Draw(&gMenus[0]);
         return;
 }
int LoadEntityData ()
Definition at line 96 of file game.c.
References ConvertFileToUseable(), CountMem(), FindKey(), FindNextFreeCachePos(), FindObject(), gEntitiesFile, gEntityData, gEntityObject, gGameData, gGameObject, Hazards_str, ParseToEntity(), ParseToObject(), ParseToStringArray(), and PrintObject().
Referenced by Setup().
 {
         int i, objects;
         entity_t *temp_ent, *pos_ent;
         //Init Entity Parse
         if( ConvertFileToUseable(gEntitiesFile, &gParser, &gEntityData, &gEntityTokens) == -1)
         {
                 printf("Failure to Parse Entity Data \n");
                 return -1;
         }
         gEntityObject = ParseToObject(gEntityTokens, gEntityData);
         printf("Size of Entity tokens: %d \n", CountMem(gEntityTokens, sizeof(jsmntok_t)));
         PrintObject(gEntityObject, gEntityData);
         Hazards_str = ParseToStringArray(FindObject(gGameObject, "Hazards"), gGameData);
         //Set Entity Dictionary
         objects = CountMem(gEntityObject->children, sizeof(object_t));
         for(i = 0; i < objects; i++)
         {
                 //Set  sprites for each object
                 if(FindKey(gEntityObject->children[i].keys, "sprite(s)", gEntityData))
                 {
                         temp_ent = ParseToEntity(&gEntityObject->children[i], gEntityData);
                         if(!temp_ent) continue;
                         pos_ent = FindNextFreeCachePos();
                         memcpy(pos_ent, temp_ent, sizeof(entity_t));
                         //if(temp) free(temp);
                 } else if ( FindObject(&gEntityObject->children[i], "sprite(s)") )
                 {
                         temp_ent = ParseToEntity(&gEntityObject->children[i], gEntityData);
                         if(!temp_ent) continue;
                         pos_ent = FindNextFreeCachePos();
                         memcpy(pos_ent, temp_ent, sizeof(entity_t));
                         //if(temp) free(temp);
                 }
         }
         return 0;
 }
int LoadGameData ()
Loads game data from GameData.json, stored in gGameData.
Returns
state 0 on success, -1 on error.
Author
Anthony Rios
Date
1/31/2016
Definition at line 60 of file game.c.
References ConvertFileToUseable(), ENTITIES_FILE_STR, FindObject(), gEntitiesFile, gGameData, gGameObject, gPowerUpsFile, gScreenHeight, gScreenWidth, JsmnToString(), JSON_FILE, ParseToObject(), ParseToVec2(), POWER_UPS_STR, PrintObject(), SCREEN_STRING, vec2_t::x, and vec2_t::y.
Referenced by Setup().
 {
         vec2_t *screen;
         object_t *temp_obj;
         //Init GameData Parse
         if(ConvertFileToUseable(JSON_FILE, &gParser, &gGameData, &gGameTokens) == -1)
         {
                 printf("Failure to Parse GameData");
                 return -1;
         }
         //Debug Checks & Object Parse
         gGameObject = ParseToObject(gGameTokens, gGameData);
         if(!gGameObject)
         {
                 printf("Object parse error");
                 return -1;
         }
         //Set Screen Dims
         temp_obj = FindObject(gGameObject, SCREEN_STRING);
         if(temp_obj)
         {
                 screen = ParseToVec2(temp_obj, gGameData);
                 gScreenWidth = screen->x;
                 gScreenHeight = screen->y;
                 printf("New Screen resolution : %d %d \n", gScreenWidth, gScreenHeight);
                 free(screen);
         }
         PrintObject(gGameObject, gGameData);
         gEntitiesFile = JsmnToString(FindObject(gGameObject, ENTITIES_FILE_STR)->values, gGameData );
         gPowerUpsFile = JsmnToString(FindObject(gGameObject, POWER_UPS_STR)->values, gGameData);
         return 0;
 }
int LoadLevelData ()
Loads level file names, and how many levels per game.
Returns
The level data.
Author
Anthony Rios
Date
3/29/2016
Definition at line 148 of file game.c.
References CountMem(), FindKey(), FindObject(), gGameData, gGameObject, gLevels, gLevelsPerGame, JsmnToInt(), JsmnToString(), LEVELS_DEFAULT, and LEVELS_NOT_DEFAULT.
Referenced by Setup().
 {
         object_t *levelObj;
         int i, lvlInt;
         //Find Levels
         levelObj = FindObject(gGameObject, "Levels");
         gLevelsPerGame = FindKey(gGameTokens, LEVELS_NOT_DEFAULT, gGameData) ? -1 : LEVELS_DEFAULT;
         if(gLevelsPerGame == -1)
         {
                 JsmnToInt(FindKey(gGameTokens, LEVELS_NOT_DEFAULT, gGameData)+1, gGameData, &gLevelsPerGame);
                 if(!gLevelsPerGame)
                         gLevelsPerGame = LEVELS_DEFAULT;
         }
         if(!levelObj)
         {
                 printf("No levels found in gameObject");
                 return -1;
         }
         //Alloc
         lvlInt = CountMem(levelObj->values, sizeof(jsmntok_t));
         gLevels = (char**) malloc(sizeof(char*) * (lvlInt + 1));
         //Load
         for(i = 0; i < lvlInt; i++)
         {
                 gLevels[i] = JsmnToString(&levelObj->values[i], gGameData);
                 if(!gLevels[i])
                 {
                         continue;
                 }
                 printf("Level : %s \n", gLevels[i]);
         }
         gLevels[lvlInt] = NULL;
         return 0;
 }
int LoadMenuData ()
Loads menu data, from files given, which are put in gMenus
Returns
The menu data.
Author
Anthony Rios
Date
3/29/2016
Definition at line 250 of file game.c.
References ConvertFileToUseable(), CountMem(), FindObject(), FindValue(), gGameData, gGameObject, gMenus, InitMenuSystem(), JsmnToString(), LoadMenu(), ParseToObject(), PrintObject(), START, and StrToGameState().
Referenced by Setup().
 {
         int i, menuCount;
         char *menuData, *menuLink, *temp_str;
         jsmntok_t *menuTok;
         object_t *menus, *menuObj;
         if(!gMenus)
         {
                 InitMenuSystem();
         }
         menus = FindObject(gGameObject, "Menus");
         menuCount = CountMem(menus->values, sizeof(jsmntok_t)) - 1;
         for(i = 0; i < menuCount; i++)
         {
                 temp_str = JsmnToString(&menus->values[i], gGameData);
                 ConvertFileToUseable(temp_str, NULL, &menuData, &menuTok);
                 if(!menuData || !menuTok)
                 {
                         continue;
                 }
                 menuObj = ParseToObject(menuTok, menuData);
                 if(!menuObj)
                 {
                         free(temp_str);
                         continue;
                 }
                 PrintObject(menuObj, menuData);
                 menuObj->name = temp_str;
                 menuLink = FindValue(menuObj, "link", menuData);
                 if(!menuLink)
                 {
                         continue;
                 }
                 LoadMenu(menuObj, menuData, StrToGameState(menuLink), START);
         }
         return 0;
 }
int LoadPowerUpData ()
After Load GameData, Before Menu. Loads the power_ups in the file given.
Returns
The power up data.
Author
Anthony Rios
Date
3/29/2016
Definition at line 196 of file game.c.
References ConvertFileToUseable(), CountMem(), FindObject(), gGameData, gGameObject, gPowerUps, gPowerUpsFile, JsmnToString(), ParseToObject(), and ParseToPowerUp().
Referenced by Setup().
 {
         jsmntok_t *power_tok;
         object_t *powers, *temp_obj;
         power_t *temp_power;
         char *power_str;
         int powerCount, i;
         temp_obj = FindObject(gGameObject, "PowerUps");
         if(!temp_obj)
         {
                 printf("Could not find powerups in GameData");
                 return -1;
         }
         gPowerUpsFile = JsmnToString(temp_obj->values, gGameData);
         ConvertFileToUseable(gPowerUpsFile, NULL, &power_str, &power_tok);
         if(!power_str || !power_tok)
         {
                 printf("Could not load power ups file : %s \n", gPowerUpsFile );
         }
         powers = ParseToObject(power_tok, power_str);
         powerCount = CountMem(powers->children, sizeof(object_t));
         gPowerUps = (power_t*) malloc(sizeof(power_t)*( powerCount+1 ));
         if(!gPowerUps)
         {
                 printf("Could not allocate power ups");
                 return -1;
         }
         for(i = 0; i < powerCount; i++)
         {
                 temp_power = ParseToPowerUp(&powers->children[i], power_str);
                 if(!temp_power)
                 {
                         printf("Power up %d could not be loaded \n", i);
                         continue;
                 }
                 gPowerUps[i] = *temp_power;
                 if(temp_power) free(temp_power);
         }
         memset(&gPowerUps[powerCount], 0, sizeof(power_t));
         return 0;
 }
int LoadSelectedLevel (int level)
Loads selected level.
Parameters
level The level.
Returns
The selected level.
See also
LoadLevel , in parselevel.c
Author
Anthony Rios
Date
3/29/2016
Definition at line 390 of file game.c.
References ConvertFileToUseable(), gLevelData, gLevelObject, gSelectedLevels, LoadLevel(), and ParseToObject().
Referenced by UpdatePowerSelectMenu().
 {
         if(!gSelectedLevels)
         {
                 printf("Levels not Selected \n");
                 return -1;
         }
         if(!gSelectedLevels[level])
         {
                 printf("Level %d not found \n", level);
                 return -1;
         }
         ConvertFileToUseable(gSelectedLevels[level], &gParser, &gLevelData, &gLevelTokens);
         if(!gLevelData || !gLevelTokens)
         {
                 printf("Unable to parse level %s \n", gSelectedLevels[level]);
         }
         gLevelObject = ParseToObject(gLevelTokens, gLevelData);
         if(!gLevelObject)
         {
                 printf("Unable to parse level %s to object \n", gSelectedLevels[level]);
         }
         if(LoadLevel(gLevelObject, gLevelData))
         {
                 perror("Unable to Load level \n");
                 return -1;
         }
         return 0;
 }
void Poll ()
Polls for all events and handles them.
Author
Anthony Rios
Date
3/29/2016
Definition at line 427 of file game.c.
References BUTTON_NO_INPUT, exitRequest, gButtonQ, gController, gEventQ, and UpdatePlaying().
Referenced by Run().
 {
         if( SDL_PollEvent(&gEventQ) )
         {
                 if(gEventQ.type == SDL_CONTROLLERDEVICEADDED || gEventQ.type == SDL_CONTROLLERDEVICEREMOVED)
                 {
                         gController = SDL_GameControllerOpen(0);
                 }
                 if(gEventQ.type == SDL_CONTROLLERBUTTONDOWN)
                 {
                         gButtonQ = (SDL_GameControllerButton) gEventQ.cbutton.button;
                         printf("Button Pressed : %d \n", gButtonQ);
                 } else
                 {
                         gButtonQ = (SDL_GameControllerButton) BUTTON_NO_INPUT;
                 }
                 if( gEventQ.type == SDL_QUIT)
                 {
                         exitRequest = 1;
                         return;
                 }
         }
         return;
 }
void RandomizeSelectedLevels ()
Randomize selected levels.
Author
Anthony Rios
Date
2/19/2016
Definition at line 343 of file game.c.
References CompareMemToMemArray(), CountMem(), gLevels, gLevelsPerGame, and gSelectedLevels.
 {
         int i, rand_i, *no_repeats;
         char **slevel_copy;
         if (CountMem(gLevels, sizeof(char*)) < gLevelsPerGame)
         {
                 printf("Levels less than min, Easy Mode - No Rand");
                 return;
         }
         //Get a copy of gSelected
         slevel_copy = (char**) malloc(sizeof(char*)*(gLevelsPerGame+1));
         memcpy(slevel_copy, gSelectedLevels, sizeof(char*)*gLevelsPerGame);
         slevel_copy[gLevelsPerGame] = 0;
         //No Repeats
         no_repeats = (int*) malloc(sizeof(int)*gLevelsPerGame+1);
         memset(no_repeats, 0, sizeof(int)*(gLevelsPerGame+1));
         //Randomize
         for(i = 0; gSelectedLevels[i]; i++)
         {
                 rand_i = rand()%gLevelsPerGame;
                 while(!CompareMemToMemArray(&rand_i, no_repeats, sizeof(int), gLevelsPerGame ))
                 {
                         rand_i = rand()%gLevelsPerGame;
                 }
                 no_repeats[i] = rand_i;
                 gSelectedLevels[i] = slevel_copy[rand_i];
         }
         free(no_repeats);
         free(slevel_copy);
 }
int Run ()
Runs the main game loop.
Returns
An int.
Author
Anthony Rios
Date
3/29/2016
Definition at line 666 of file game.c.
References Draw(), exitRequest, FRAME_DELAY, gCurrentTime, gDelay, Poll(), and Update().
Referenced by main().
 {
         while(!exitRequest)
         {
                 Poll();
                 Update();
                 Draw();
                 gDelay = SDL_GetTicks() - gCurrentTime;
                 SDL_Delay(gDelay > FRAME_DELAY ? 0 : gDelay);
         }
         return 0;
 }
int SelectLevels ()
Select the levels randomly from the available levels, stores in gSelectedLevels.
Returns
0 on success, -1 on error
Author
Anthony Rios
Date
1/31/2016
Definition at line 297 of file game.c.
References CompareMemToMemArray(), gLevels, gLevelsPerGame, and gSelectedLevels.
Referenced by Setup().
 {
         int i, rand_i, *no_repeats, type_i;
         int levels = 0;
         //Count
         while(gLevels[levels])
         {
                 levels++;
         }
         type_i = sizeof(int);
         //Alloc
         gSelectedLevels = (char**) malloc(sizeof(char*)*levels+1);
         no_repeats = (int*) malloc(sizeof(int)*(levels+1));
         if(!gSelectedLevels) return -1;
         if(!no_repeats) return -1;
         //Select
         memset(no_repeats, 0, sizeof(int));
         for (i = 0; i < gLevelsPerGame; i++)
         {
                 rand_i = rand()%levels;
                 if(i >= levels)
                 {
                         break;
                 }
                 while(!CompareMemToMemArray(&rand_i, no_repeats, type_i, levels ))
                 {
                         rand_i = rand()%levels;
                 }
                 no_repeats[i] = rand_i;
                 gSelectedLevels[i] = gLevels[rand_i];
         }
         gSelectedLevels[i] = NULL;
         free(no_repeats);
         return 0;
 }
int Setup ()
Loads files and images for game.
Returns
state returns 0 on success, -1 on error
Author
Anthony Rios
Date
1/31/2016
Definition at line 592 of file game.c.
References gController, InitAISystem(), InitEntitySystem(), InitGraphics(), InitMenuSystem(), LoadEntityData(), LoadGameData(), LoadLevelData(), LoadMenuData(), LoadPowerUpData(), and SelectLevels().
Referenced by main().
 {
         //sprite_t *test_sprite;
         //vec2_t test_vec = {0,0};
         srand(SDL_GetTicks());
         //atexit(Shutdown);
         if(LoadGameData())
         {
                 perror("Loading game data went wrong");
                 return -1;
         }
         if(InitGraphics())
         {
                 perror("Initializing entity system went wrong");
                 return -1;
         }
         if(InitEntitySystem())
         {
                 perror("Initializing entity system went wrong");
                 return -1;
         }
         if(InitMenuSystem())
         {
                 perror("Initialize Menu system went wrong");
                 return -1;
         }
         if(InitAISystem())
         {
                 perror("Initialize AI system went wrong");
                 return -1;
         }
         if(LoadEntityData())
         {
                 perror("Loading entity data went wrong");
                 return -1;
         }
         if(LoadMenuData())
         {
                 perror("Shit Happens");
                 return -1;
         }
         if(LoadLevelData())
         {
                 perror("Loading level data went wrong");
                 return -1;
         }
         if(LoadPowerUpData())
         {
                 perror("Loading entity data went wrong");
                 return -1;
         }
         if(SelectLevels())
         {
                 perror("Selecting levels went wrong");
                 return -1;
         }
         gController = SDL_GameControllerOpen(0);
         //PrintObject(gLevelObject, gLevelData);
         //test_sprite = LoadSprite("Sprite/UI/NESController.png",0);
         //test_sprite->mCurrentFrame = LoadAnimation(test_sprite->mSize.x, test_sprite->mSize.y, test_sprite->mSize.x, test_sprite->mSize.y);
         //FreeSprite(test_sprite);
         return 0;
 }
void Shutdown ()
Definition at line 679 of file game.c.
Referenced by main().
 {
         return;
 }
void Update ()
Definition at line 458 of file game.c.
References CHOOSE, DrawChoose(), DrawGuess(), DrawPlaying(), DrawSplash(), DrawStart(), exitRequest, FindValue(), gButtonQ, gCurrentTime, gGameData, gGameObject, gGameState, gMenus, gSplash, GUESS, LoadSprite(), PLAYING, SPLASH, SPLASH_SCREEN, START, and UpdatePlaying().
Referenced by FindMenuFromGameState(), and Run().
 {
         char *splash;
         gCurrentTime = SDL_GetTicks();
         switch(gGameState)
         {
         case(SPLASH):
                 {
                         if(!gSplash)
{
                                 splash = FindValue(gGameObject, SPLASH_SCREEN, gGameData);
                                 if(!splash)
{
                                         printf("SplashScreen key not found in gameData \n");
                                 } else {
                                         gSplash = LoadSprite(splash, 0);
                                         if(!gSplash)
{
                                                 printf("Splash screen could not be loaded \n");
                                         }
                                 }
                         }
                         //If you pressed a button
                         if(gButtonQ != -1)
{
                                 gGameState = START;
                         }
                         break;
                 }
         case(START):
                 {
                         if(!gMenus)
{
                                 printf("No menus loaded");
                                 exitRequest = 1;
                                 return;
                         }
                         if(gButtonQ != -1)
{
                                 gMenus[0].Update(&gMenus[0], gButtonQ);
                         }
                         break;
                 }
         case(GUESS):
                 {
                         if(!gMenus)
{
                                 printf("No menus loaded");
                                 exitRequest = 1;
                                 return;
                         }
                         if(gButtonQ != -1)
{
                                 gMenus[1].Update(&gMenus[1], gButtonQ);
                         }
                         break;
                 }
         case(CHOOSE):
                 {
                         if(!gMenus)
{
                                 printf("No menus loaded");
                                 exitRequest = 1;
                                 return;
                         }
                         if(gButtonQ != -1)
{
                                 gMenus[2].Update(&gMenus[2], gButtonQ);
                         }
                         break;
                 }
         case(PLAYING):
                 {
                         UpdatePlaying();
                         break;
                 }
         default:
                 break;
         }
 }
void UpdatePlaying ()
Updates the playing game state.
Author
Anthony Rios
Date
3/29/2016
Definition at line 776 of file game.c.
References RunEntities(), and RunPhysics().
Referenced by Poll(), and Update().
 {
         RunEntities();
         RunPhysics();
 }
Variable Documentation
int exitRequest = 0
The integer to be changed to exit
Definition at line 22 of file game.c.
Referenced by DrawChoose(), DrawGuess(), DrawStart(), InitPlayer(), Poll(), Run(), and Update().
SDL_GameControllerButton gButtonQ
The button qeueu updated with the current button pressed
Definition at line 49 of file game.c.
Referenced by Poll(), ThinkPlayer(), and Update().
SDL_GameController* gController = NULL
The controller
Definition at line 48 of file game.c.
Referenced by Poll(), Setup(), and ThinkPlayer().
char* gCurrentPowerUpName = NULL
The current power up name
Definition at line 43 of file game.c.
Referenced by UpdatePowerSelectMenu().
unsigned int gCurrentTime = 0
The current time , updated from last update call
Definition at line 50 of file game.c.
Referenced by InitPlayer(), JumpAI(), MoveAI(), NothingAI(), Run(), RunEntities(), ThinkGeneric(), ThinkPlayer(), Update(), and WalkAI().
int gDelay = 0
Definition at line 23 of file game.c.
Referenced by Run().
char* gEntitiesFile = NULL
The name of the entities file
Definition at line 39 of file game.c.
Referenced by LoadEntityData(), and LoadGameData().
char* gEntityData
The current parsed string of the entity file
Definition at line 37 of file game.c.
Referenced by LoadEntityData().
entity_t* gEntityDictionary
Entities loaded from files AKA cached entities
Definition at line 41 of file game.c.
Referenced by FindCachedEntity(), FindNextFreeCachePos(), and InitEntitySystem().
object_t* gEntityObject
The entity object
Definition at line 34 of file game.c.
Referenced by LoadEntityData().
jsmntok_t* gEntityTokens
The entity jsmn tokens
Definition at line 31 of file game.c.
SDL_Event gEventQ
The event qeueu update with all SDL_Events
Definition at line 47 of file game.c.
Referenced by Poll().
char* gGameData
Game Data File - holding the contents of file via string
Definition at line 36 of file game.c.
Referenced by LoadEntityData(), LoadGameData(), LoadLevelData(), LoadMenuData(), LoadPowerUpData(), Update(), and UpdatePowerUpMenu().
object_t* gGameObject
The game object
Definition at line 33 of file game.c.
Referenced by LoadEntityData(), LoadGameData(), LoadLevelData(), LoadMenuData(), LoadPowerUpData(), Update(), and UpdatePowerUpMenu().
GameState gGameState = SPLASH
State of the game
Definition at line 44 of file game.c.
Referenced by Draw(), ThinkPlayer(), TouchGoal(), Update(), UpdatePowerSelectMenu(), UpdatePowerUpMenu(), and UpdateVerticalMenu().
jsmntok_t* gGameTokens
Tokens for GameData
Definition at line 30 of file game.c.
char* gLevelData
Information describing the current level
Definition at line 38 of file game.c.
Referenced by LoadSelectedLevel().
object_t* gLevelObject
The current level object
Definition at line 35 of file game.c.
Referenced by LoadSelectedLevel().
char** gLevels = NULL
The level names
Definition at line 26 of file game.c.
Referenced by LoadLevelData(), RandomizeSelectedLevels(), and SelectLevels().
int gLevelsPerGame = LEVELS_DEFAULT
The levels per game
Definition at line 24 of file game.c.
Referenced by LoadLevelData(), RandomizeSelectedLevels(), SelectLevels(), and UpdatePowerUpMenu().
jsmntok_t* gLevelTokens
The level jsmn tokens
Definition at line 32 of file game.c.
jsmn_parser gParser
The global jsmn parser
Definition at line 25 of file game.c.
power_t* gPowerUps
The loaded power ups
Definition at line 42 of file game.c.
Referenced by FindPower(), InitPlayer(), LoadPowerUpData(), and UpdatePowerUpMenu().
char* gPowerUpsFile = NULL
The name of the power ups file
Definition at line 40 of file game.c.
Referenced by LoadGameData(), and LoadPowerUpData().
char** gSelectedLevels = NULL
The selected levels to load
Definition at line 27 of file game.c.
Referenced by LoadSelectedLevel(), RandomizeSelectedLevels(), and SelectLevels().
char** gSelectedPowerUps = NULL
The power ups the player selects
Definition at line 28 of file game.c.
Referenced by LoadMenu(), TouchGoal(), UpdatePowerSelectMenu(), and UpdatePowerUpMenu().
sprite_t* gSplash = NULL
The splash screen sprite
Definition at line 45 of file game.c.
Referenced by DrawSplash(), and Update().
char** gUsedPowerUps = NULL
The used power ups for this game run
Definition at line 29 of file game.c.
Referenced by TouchGoal(), UpdatePowerSelectMenu(), and UpdatePowerUpMenu().
vec2_t gZeroPos = {0,0}
Definition at line 46 of file game.c.
Referenced by InitPlayer().