Dumb-ways-to-memorize: dumb-ways-to-memorize/entity.c File Reference
entity.c File Reference
#include "globals.h"
#include "entity.h"
#include "graphics.h"
#include "quick_controller.h"
#include <stdio.h>
#include <math.h>
#include "player.h"
#include "parselevel.h"
#include "parsepowerup.h"
Functions
void DrawGeneric (entity_t *self)
void DrawPlayer (entity_t *self)
void ThinkGeneric (entity_t *self)
void ThinkPlayer (entity_t *self)
void ThinkEnemy (entity_t *self)
void TouchGeneric (entity_t *self, entity_t *other, int type)
void TouchPlayer (entity_t *self, entity_t *other, int type)
void TouchEnemy (entity_t *self, entity_t *other, int type)
void TouchGoal (entity_t *self, entity_t *other, int type)
int InitEntitySystem ()
entity_t * InitNewEntity ()
entity_t * FindNextFreeCachePos ()
void DrawEntities ()
void RunEntities ()
entity_t * FindCachedEntity (const char *name)
entity_t * FindEntity (const char *name)
entity_t * FindFreeEntity (int *position)
entity_t * LookForEntityAtPos (vec2_t position)
int Distance2Entity (entity_t *self, entity_t *other)
void FreeEntity (entity_t *ent)
void FreeNonPlayerEntities ()
void ShutdownEntitySystem ()
Variables
entity_t * gEntities = NULL
int gLastEntity = 0
char ** Hazards_str = NULL
char * Collisions_str [] = {"static", "ragdoll", "clip", 0}
char * EntityStates_str [] = {"alive", "dead", "other", 0}
Function Documentation
int Distance2Entity (entity_t * self, entity_t * other)
Distance 2 entity other from entity self.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
[in,out] other If non-null, the other entity.
Returns
An int.
Author
Anthony Rios
Date
3/29/2016
Definition at line 371 of file entity.c.
Referenced by ThinkEnemy().
 {
         int x, y;
         x = self->mPosition.x - other->mPosition.x;
         y = self->mPosition.y - self->mPosition.y;
         return powf(powf(x, 2) + powf(y, 2), (float) 1/2);
 }
void DrawEntities ()
Draw entities, if they have draw functions.
Author
Anthony Rios
Date
3/29/2016
Definition at line 264 of file entity.c.
References Draw(), gEntities, and MAX_ENTITIES.
Referenced by DrawPlaying().
 {
         int i;
         if(!gEntities)
         {
                 return;
         }
         for(i = 0; i < MAX_ENTITIES; i++)
         {
                 if(!gEntities[i].Draw)
                 {
                         continue;
                 }
                 gEntities[i].Draw(&gEntities[i]);
         }
 }
void DrawGeneric (entity_t * self)
Draws the entity via self->mAnimation if set, or the first sprite which is idle.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
Author
Anthony Rios
Date
3/29/2016
Definition at line 17 of file entity.c.
References ANIMATION_IDLE, DrawSprite(), and gRenderer.
Referenced by InitPlayer(), LoadLevel(), and ParseToEntity().
 {
         if(!self)
         {
                 return;
         }
         if(!self->mSprites)
         {
                 return;
         }
         if(self->mAnimation)
         {
                 //IncrementFrame(self->mAnimation);
                 DrawSprite(self->mAnimation, &self->mCurrentFrame, &self->mPosition, gRenderer);
         } else
         {
                 //IncrementFrame(self->mSprites[ANIMATION_IDLE]);
                 DrawSprite(self->mSprites[ANIMATION_IDLE], &self->mCurrentFrame, &self->mPosition, gRenderer);
         }
 }
void DrawPlayer (entity_t * self)
Definition at line 40 of file entity.c.
 {
         //DrawSprite(self->mSprites, &self->mPosition, gRenderer);
 }
entity_t* FindCachedEntity (const char * name)
Searches for the cached entity whose name matches given str.
Parameters
name The name of the entity.
Returns
null if it fails, else the found cached entity.
Author
Anthony Rios
Date
3/29/2016
Definition at line 301 of file entity.c.
References gEntityDictionary, and MAX_ENTITIES.
Referenced by AttackAI(), InitPlayer(), JumpAI(), LoadLevel(), MoveAI(), NothingAI(), ParseToPowerUp(), and WalkAI().
 {
         int i;
         for(i = 0; i < MAX_ENTITIES; i++)
         {
                 if(!gEntityDictionary[i].mName)
                         break;
                 if(!strcmp(name, gEntityDictionary[i].mName))
                 {
                         return &gEntityDictionary[i];
                 }
         }
         return NULL;
 }
entity_t* FindEntity (const char * name)
Searches for the first entity with the name of given str.
Parameters
name The name of the searched for entity.
Returns
null if it fails, else the found entity.
Author
Anthony Rios
Date
3/29/2016
Definition at line 316 of file entity.c.
References gEntities, and MAX_ENTITIES.
Referenced by ThinkEnemy().
 {
         int i;
         for(i = 0; i < MAX_ENTITIES; i++)
         {
                 if(!gEntities[i].mName)
                         continue;
                 if(!strcmp(name, gEntities[i].mName))
                 {
                         return &gEntities[i];
                 }
         }
         return NULL;
 }
entity_t* FindFreeEntity (int * position)
Searches for the first free entity.
Parameters
[in,out] position If non-null, the position.
Returns
null if it fails, else the found free entity.
Author
Anthony Rios
Date
3/29/2016
Definition at line 331 of file entity.c.
References gEntities, gLastEntity, and MAX_ENTITIES.
Referenced by InitNewEntity().
 {
         int i;
         for(i = gLastEntity; i < MAX_ENTITIES; i++)
         {
                 if(!gEntities[i].mName)
                 {
                         if(position)
                                 *position = i;
                         return &gEntities[i];
                 }
         }
         for(i = 0; i < gLastEntity; i++)
         {
                 if(!gEntities[i].mName)
                 {
                         if(position)
                                 *position = i;
                         return &gEntities[i];
                 }
         }
         return NULL;
 }
entity_t* FindNextFreeCachePos ()
Searches for the next free cache position in gEntitiesDictionary.
Returns
null if it fails, else the found free cache position.
Author
Anthony Rios
Date
3/29/2016
Definition at line 250 of file entity.c.
References gEntityDictionary, and MAX_ENTITIES.
Referenced by LoadEntityData().
 {
         int i;
         for(i = 0; gEntityDictionary[i].mName; i++)
         {
                 ;
         }
         if(&gEntityDictionary[i] > &gEntityDictionary[MAX_ENTITIES])
         {
                 return NULL;
         }
         return &gEntityDictionary[i];
 }
void FreeEntity (entity_t * ent)
Free entity.
Note
right now it just acts like memset(0) on entities in the global Entities scope. But it free's any other data that isn't globally set.
Parameters
[in,out] ent If non-null, the ent.
Author
Anthony Rios
Date
3/29/2016
Definition at line 379 of file entity.c.
References gEntities, and MAX_ENTITIES.
Referenced by Destroy(), FreeNonPlayerEntities(), LoadLevel(), ShutdownEntitySystem(), ThinkGeneric(), and ThinkPlayer().
 {
         int i, isGlobal = 0;
         if(!ent)
                 return;
         i = 0;
         //if(ent->mSprites)
         //{
                 //while(ent->mSprites[i])
                 //{
                         //FreeSprite(ent->mSprites[i]);
                         //i++;
                 //}
                 //free(ent->mSprites);
         //}
         for(i = 0; i < MAX_ENTITIES; i++)
         {
                 if(ent == &gEntities[i])
                 {
                         isGlobal = 1;
                         memset(ent, 0, sizeof(entity_t));
                 }
         }
         if(!isGlobal)
         {
                 free(ent);
         }
 }
void FreeNonPlayerEntities ()
Frees the non player entities, use for Destroy World.
Author
Anthony Rios
Date
3/29/2016
Definition at line 409 of file entity.c.
References FreeEntity(), gEntities, gPlayer, and MAX_ENTITIES.
Referenced by LoadLevel(), and ThinkPlayer().
 {
         int i , entities;
         if(!gEntities)
         {
                 return;
         }
         for(i = 0; i < MAX_ENTITIES; i++)
         {
                 if(&gEntities[i] == (entity_t*) gPlayer)
                 {
                         continue;
                 }
                 FreeEntity(&gEntities[i]);
         }
 }
int InitEntitySystem ()
Init entity system.
Returns
An int of failure state. 0 if good, -1 if error.
Author
Anthony Rios
Date
3/29/2016
Definition at line 217 of file entity.c.
References gEntities, gEntityDictionary, gLastEntity, and MAX_ENTITIES.
Referenced by Setup().
 {
         if( (gEntities = (entity_t*) malloc(sizeof(entity_t)*MAX_ENTITIES)) == NULL )
         {
                 printf("Couldn't alloc EntitySys");
                 return -1;
         }
         if( (gEntityDictionary = (entity_t*) malloc(sizeof(entity_t)*MAX_ENTITIES)) == NULL )
         {
                 printf("Couldn't alloc EntitySys");
                 return -1;
         }
         memset(gEntities, 0, sizeof(entity_t)*MAX_ENTITIES);
         memset(gEntityDictionary, 0, sizeof(entity_t)*MAX_ENTITIES);
         gLastEntity = 0;
         return 0;
 }
entity_t* InitNewEntity ()
Init new entity in the memory of global entity space.
Returns
null if it fails, else a pointer to an entity_t.
Author
Anthony Rios
Date
3/29/2016
Definition at line 235 of file entity.c.
References FindFreeEntity(), gEntities, and gLastEntity.
Referenced by InitPlayer(), LoadLevel(), and Spawn().
 {
         int pos;
         entity_t *retVal;
         if(gEntities == NULL)
         {
                 printf("Entity system unintialiazeed");
                 exit(-1);
         }
         retVal = FindFreeEntity(&pos);
         gLastEntity = pos;
         return retVal;
 }
entity_t* LookForEntityAtPos (vec2_t position)
Look for entity at position.
Parameters
position The position.
Returns
null if it fails, else a pointer to an entity_t.
Author
Anthony Rios
Date
3/29/2016
Definition at line 355 of file entity.c.
References gEntities, MAX_ENTITIES, vec2_t::x, and vec2_t::y.
Referenced by GetAtPoint().
 {
         int i;
         for(i = 0; i < MAX_ENTITIES; i++)
         {
                 if(!gEntities[i].mName)
                         continue;
                 if( (gEntities[i].mPosition.x > position.x > gEntities[i].mPosition.x + gEntities[i].mSprites[0]->mSize.x)
                         && (gEntities[i].mPosition.y > position.y > gEntities[i].mPosition.x + gEntities[i].mSprites[0]->mSize.y))
                 {
                         return &gEntities[i];
                 }
         }
         return NULL;
 }
void RunEntities ()
Executes the entities think functions.
Note
I think I have the logic wrong..
Author
Anthony Rios
Date
3/29/2016
Definition at line 281 of file entity.c.
References gCurrentTime, gEntities, and MAX_ENTITIES.
Referenced by UpdatePlaying().
 {
         int i;
         if(!gEntities)
         {
                 return;
         }
         for(i = 0; i < MAX_ENTITIES; i++)
         {
                 if(!gEntities[i].Think || !gEntities[i].mName)
                 {
                         continue;
                 }
                 if( gCurrentTime > gEntities[i].mNextThink)
                 {
                         gEntities[i].Think(&gEntities[i]);
                 }
         }
 }
void ShutdownEntitySystem ()
Shutdown entity system, frees all the entities.
Author
Anthony Rios
Date
3/29/2016
Definition at line 427 of file entity.c.
References FreeEntity(), gEntities, and MAX_ENTITIES.
 {
         int i;
         if(!gEntities)
                 return;
         for(i = 0; i < MAX_ENTITIES; i++)
         {
                 if(!gEntities[i].mName)
                         continue;
                 FreeEntity(&gEntities[i]);
         }
         free(gEntities);
 }
void ThinkEnemy (entity_t * self)
The modular think function for enemy entities with an AI.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
Author
Anthony Rios
Date
3/29/2016
Definition at line 102 of file entity.c.
References AI_FLAG_CHECK_OBJECT, AI_FLAG_CHECK_PLAYER, AI_VAR_CHECK, Distance2Entity(), FindEntity(), GetFunctionAI, and gPlayer.
Referenced by LoadLevel().
 {
         if(!self) return;
         if(!self->mData) return;
         if(self->mData->mFlags & AI_FLAG_CHECK_OBJECT)
         {
                 if(!self->mData->mObjectCheck)
                 {
                         self->mData = self->mData->mLink;
                         return;
                 }
                 if( Distance2Entity(self, FindEntity(self->mData->mObjectCheck)) < self->mData->mVariables[AI_VAR_CHECK])
                 {
                         if(GetFunctionAI(self->mData))
{
                                 GetFunctionAI(self->mData)(self);
                         }
                 }
         } else if (self->mData->mFlags & AI_FLAG_CHECK_PLAYER)
         {
                 if(Distance2Entity(self, (entity_t*)gPlayer) < self->mData->mVariables[AI_VAR_CHECK])
                 {
                         if(GetFunctionAI(self->mData))
{
                                 GetFunctionAI(self->mData)(self);
                         }
                 }
         } else
         {
                 if(GetFunctionAI(self->mData))
                 {
                         GetFunctionAI(self->mData)(self);
                 }
         }
 }
void ThinkGeneric (entity_t * self)
Generic think function, checks health and dies when health <= 0
Parameters
[in,out] self If non-null, the class instance that this method operates on.
Author
Anthony Rios
Date
3/29/2016
Definition at line 45 of file entity.c.
References FRAME_DELAY, FreeEntity(), and gCurrentTime.
Referenced by ParseToEntity().
 {
         if(!self)
         {
                 return;
         }
         if(self->mHealth <= 0)
         {
                 self->Think = FreeEntity;
         }
         self->mNextThink = gCurrentTime + 2*FRAME_DELAY;
 }
void ThinkPlayer (entity_t * self)
The player think function, handles lives ,gamestate switching , and input.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
Author
Anthony Rios
Date
3/29/2016
Definition at line 59 of file entity.c.
References BUTTON_NO_INPUT, DoPlayerThink(), FreeEntity(), FreeNonPlayerEntities(), gButtonQ, gController, gCurrentPowerUp, gCurrentTime, gGameState, gPlayer, gPlayerLives, GUESS, PLAYER_LIVES, and START.
Referenced by InitPlayer().
 {
         //Do input control
         if(!self) return;
         if(gButtonQ != BUTTON_NO_INPUT)
         {
                 DoPlayerThink(self, gButtonQ);
         } else if(SDL_GameControllerGetButton(gController, SDL_CONTROLLER_BUTTON_DPAD_LEFT))
         {
                 DoPlayerThink(self, SDL_CONTROLLER_BUTTON_DPAD_LEFT);
         } else if(SDL_GameControllerGetButton(gController, SDL_CONTROLLER_BUTTON_DPAD_RIGHT))
         {
                 DoPlayerThink(self, SDL_CONTROLLER_BUTTON_DPAD_RIGHT);
         } else if(SDL_GameControllerGetButton(gController, SDL_CONTROLLER_BUTTON_B))
         {
                 if(gCurrentPowerUp)
                 {
                         //If infinite use
                         if(!gCurrentPowerUp->UpdateUse)
{
                                 self->PowerUp(gCurrentPowerUp);
                         }
                 }
         }
         self->mNextThink = gCurrentTime + 1; //Player always thinks
         if(self->mHealth < 0)
         {
                 if(gPlayerLives < 0)
                 {
                         printf("You died, Game over. Start a new game");
                         FreeEntity(gPlayer);
                         gPlayerLives = PLAYER_LIVES;
                         FreeNonPlayerEntities();
                         gGameState = START;
                 } else
                 {
                         printf("You died, select your powerups again \n");
                         gPlayerLives--;
                         gGameState = GUESS;
                 }
         }
 }
void TouchEnemy (entity_t * self, entity_t * other, int type)
The touch function for an enemy, currently does nothing.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
[in,out] other If non-null, the other.
type The type.
Author
Anthony Rios
Date
3/30/2016
Definition at line 196 of file entity.c.
References COLLISION_TYPE_RAGDOLL, and COLLISION_TYPE_STATIC.
Referenced by LoadLevel().
 {
         switch(other->mCollisionType)
         {
         case COLLISION_TYPE_STATIC:
                 break;
         case COLLISION_TYPE_RAGDOLL:
                 break;
         default:
                 break;
         }
 }
void TouchGeneric (entity_t * self, entity_t * other, int type)
Generic touch function, Receives pain from touch and inflict pain on touch depending on hazard types.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
[in,out] other If non-null, the other.
type The type.
Author
Anthony Rios
Date
3/29/2016
Definition at line 139 of file entity.c.
References ANIMATION_HIT, COLLISION_TYPE_RAGDOLL, COLLISION_TYPE_STATIC, CountMem(), FRAME_DELAY, HAZARD_DAMAGE, and HAZARD_STUN_FRAMES.
Referenced by ParseToEntity().
 {
         switch(type)
         {
         case(COLLISION_TYPE_STATIC):
                 {
                         if(! (other->mHazards & self->mHazards) )
{
                                 self->mHealth -= HAZARD_DAMAGE;
                                 self->mAnimation = ANIMATION_HIT >= CountMem(self->mSprites, sizeof(sprite_t*)) ? NULL : self->mSprites[ANIMATION_HIT];
                                 self->mNextThink += HAZARD_STUN_FRAMES*FRAME_DELAY;
                         }
                         break;
                 }
         case(COLLISION_TYPE_RAGDOLL):
                 {
                         if(! (other->mHazards & self->mHazards) )
{
                                 self->mHealth -= HAZARD_DAMAGE;
                                 other->mHealth -= HAZARD_DAMAGE;
                                 self->mAnimation = ANIMATION_HIT >= CountMem(self->mSprites, sizeof(sprite_t*)) ? NULL : self->mSprites[ANIMATION_HIT];
                         }
                 }
         default:
                 break;
         }
 }
void TouchGoal (entity_t * self, entity_t * other, int type)
The touch function for the goal entity / flag. Switches gamestate based on if you won or should go to the next level.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
[in,out] other If non-null, the other entity it touched.
type The type.
Author
Anthony Rios
Date
3/29/2016
Definition at line 209 of file entity.c.
References CHOOSE, CountMem(), gGameState, gPlayer, gSelectedPowerUps, gUsedPowerUps, and START.
Referenced by LoadLevel().
 {
         if(other == gPlayer)
         {
                 gGameState = CountMem(gUsedPowerUps, sizeof(char*)) >= CountMem(gSelectedPowerUps, sizeof(char*)) ? START : CHOOSE;
         }
 }
void TouchPlayer (entity_t * self, entity_t * other, int type)
The player touch function called on collision. If he touches a hazard, he gets damaged.
Parameters
[in,out] self If non-null, the class instance that this method operates on.
[in,out] other If non-null, the other.
type The type.
Author
Anthony Rios
Date
3/30/2016
Definition at line 168 of file entity.c.
References ANIMATION_HIT, COLLISION_TYPE_RAGDOLL, COLLISION_TYPE_STATIC, CountMem(), FRAME_DELAY, HAZARD_DAMAGE, and HAZARD_STUN_FRAMES.
Referenced by InitPlayer().
 {
         switch(type)
         {
         case(COLLISION_TYPE_STATIC):
                 {
                         if(! (other->mHazards & self->mHazards) )
{
                                 self->mHealth -= HAZARD_DAMAGE;
                                 self->mAnimation = ANIMATION_HIT >= CountMem(self->mSprites, sizeof(sprite_t*)) ? NULL : self->mSprites[ANIMATION_HIT];
                                 self->mNextThink += HAZARD_STUN_FRAMES*FRAME_DELAY;
                         }
                         break;
                 }
         case(COLLISION_TYPE_RAGDOLL):
                 {
                         if(! (other->mHazards & self->mHazards) )
{
                                 self->mHealth -= HAZARD_DAMAGE;
                                 self->mAnimation = ANIMATION_HIT >= CountMem(self->mSprites, sizeof(sprite_t*)) ? NULL : self->mSprites[ANIMATION_HIT];
                                 self->mNextThink += HAZARD_STUN_FRAMES*FRAME_DELAY;
                         }
                         break;
                 }
         }
 }
Variable Documentation
char* Collisions_str[] = {"static", "ragdoll", "clip", 0}
The collisions type strings for parsing
Definition at line 14 of file entity.c.
Referenced by StrToCollisionType().
char* EntityStates_str[] = {"alive", "dead", "other", 0}
The entity state strings for parsing
Definition at line 15 of file entity.c.
Referenced by StrToEntityState().
entity_t* gEntities = NULL
The memory for entities that are currently running in the game
Definition at line 11 of file entity.c.
Referenced by DrawEntities(), FindEntity(), FindFreeEntity(), FreeEntity(), FreeNonPlayerEntities(), GetWorld(), InitEntitySystem(), InitNewEntity(), LookForEntityAtPos(), RunEntities(), RunPhysics(), and ShutdownEntitySystem().
int gLastEntity = 0
The last entity that was free'd or created
Definition at line 12 of file entity.c.
Referenced by FindFreeEntity(), InitEntitySystem(), and InitNewEntity().
char** Hazards_str = NULL
The hazards string array which is defined in the gamedata file
Definition at line 13 of file entity.c.
Referenced by LoadEntityData(), and StrToHazard().